var OmniGo = {};
OmniGo.event = OmniGo.event || {
  overrides: {},
  overridesTxt:
    '{\n    "resultsByDistanceGenderFilter": {\n        "arguments": "result",\n        "body": "return result.class.toLowerCase().indexOf(\'ebike\') === -1 && result.class.toLowerCase().indexOf(\'tandem\') === -1"\n    }\n}',
  id: "3fcae798-3dfd-4a78-afed-a28bea41f686",
  parentId: null,
  ownerId: "1065b7d9-24e0-4223-a831-3a5d7eb26342",
  eventTypeId: "3",
  name: "2023 BWR Canada",
  urlPath: "bwr-bc-2023",
  regUrl: "https://www.bikereg.com/belgian-waffle-ride-british-columbia-2023",
  resultsPdfUrl: null,
  resultsUrl: "",
  summary: "",
  date: "2023-05-28T14:00:00.000Z",
  license: "",
  mobileResultsUrl: null,
  showTotalTimeBeforeFinish: false,
  city: "Vancouver Island",
  state: "BC",
  country: "2",
  thumb:
    "https://s3.us-west-2.amazonaws.com/static.omnigoevents.com/www/img/events/bwr.png",
  img: "https://s3.us-west-2.amazonaws.com/static.omnigoevents.com/www/img/events/bwr.png",
  resultNotes: null,
  pageHtml:
    '<style>\n    html,\n    body {\n        /*background-color:black;\n        color:white;*/\n        font-size: 15px;\n        text-align:center;\n    }\n    html {\n        scroll-behavior: smooth;\n    }\n    .logo {\n        border-radius:5px;\n        width:100%;\n    }\n    body a.navbar-brand {\n        visibility:initial;\n    }\n   nav.navbar.fixed-bottom {\n      display:none;\n   }\n</style>\n\n    <img alt="Belgian Waffle Ride - British Columbia Logo" \n    width="800" \n    style="border-radius:5px; width: 100%; height:auto; margin-bottom:20px; max-width:800px"  \n    class="logo" \n    src="https://s3.us-west-2.amazonaws.com/static.omnigoevents.com/www/img/events/BWR_BC_2023_BANNER_800x.jpg">\n\n\n<div class="row">\n    <div class="col">\n        <!--<a class="btn btn-primary btn-lg" href="https://www.bikereg.com/belgian-waffle-ride-british-columbia-2023">Register</a>-->\n\n        <h2>Canada</h2>\n        <a class="btn btn-primary btn-lg ml-2 mb-2" href="/events/bwr-bc-2023/results/">Results</a>\n        <a class="btn btn-primary btn-lg ml-2 mb-2" href="/events/bwr-bc-2023/results/strava-lite">Category (Strava) Results</a>\n\n        <h2>Quadrupel Crown of Gravel</h2>\n        <a class="btn btn-primary btn-lg ml-2 mb-2" href="/series/quadcrown-2023/results">Results</a>\n\n    </div>\n</div>\n\n\n\n',
  pageJs: "",
  ageAtEvent: false,
  lapAwardConfig: null,
  importFilterFn:
    "reg['Category Entered / Merchandise Ordered'] && \nreg['Category Entered / Merchandise Ordered'].toLowerCase().indexOf('vip dinner') === -1 && \nreg['Category Entered / Merchandise Ordered'].toLowerCase().indexOf('expo') === -1 &&\nreg['Category Entered / Merchandise Ordered'].toLowerCase().indexOf('donation') === -1 &&\nreg['Category Entered / Merchandise Ordered'].toLowerCase().indexOf('aid station') === -1 && \nreg['Category Entered / Merchandise Ordered'].toLowerCase().indexOf('traffic control') === -1 &&\nreg['Category Entered / Merchandise Ordered'].toLowerCase().indexOf('volunteer') === -1",
  importClassMappings:
    '{\n    "Waffle": "Waffle",\n    "Wafer": "Wafer",\n    "Wanna": "Wanna",\n\n    "Waffle Junior 18 and Under": "Waffle",\n    "Waffle U23": "Waffle",\n\n    "Wafer Junior 18 and Under": "Wafer",\n    "Wafer U23": "Wafer",\n\n    "Wanna Junior 18 and Under": "Wanna",\n    "Wanna U23": "Wanna",\n\n    "Waffle Tandem": "Waffle: Tandem",\n\n    "Wafer Tandem": "Wafer: Tandem",\n    "Wafer- EBike": "Wafer: EBike",\n\n    "Wanna Tandem": "Wanna: Tandem",\n    "Wanna EBike": "Wanna: EBike"\n}',
  importValueMaps:
    "[\"{\\\"onBatch\\\":\\\"/* remove the following */\\\\nconst toRemove = [];\\\\nrecords = records.filter(record => !toRemove.find(rem => record['External Id'] === rem));\\\\n\\\\n/* adjust the following genders */\\\\nconst genders = {M:[10203271,9924254,9581764,10149055,9602748,9917706,10192605], F:[9912826, 10276315, 10332600]};\\\\nrecords = records.map(record => ({\\\\n    ...record, \\\\n    Gender: genders['M'].indexOf(record['External Id']) > -1 ? 'M' : (genders['F'].indexOf(record['External Id']) > -1 ? 'F' : record['Gender']) \\\\n}));\\\\n\\\\n/* adjust the following classes */\\\\n/* records = records.map(record => ({...record, Class: record['External Id'] === 9058895 ? 'Wafer' : record['Class'] })); */\\\\n\\\\n/* adjust team names */\\\\nconst teamsMap = {\\\\n    '8628273': 'Jukebox',\\\\n    '8629940': 'Jukebox'\\\\n};\\\\nrecords = records.map(record => ({\\\\n    ...record,\\\\n    Team: teamsMap[''+record['External Id']] || record['Team']\\\\n}));\\\\n\\\\nreturn records;\\\",\\\"onItem\\\":\\\"/* Cleanup characters */\\\\nif (key === 'Last Name') {\\\\n    if (value === 'Auerbach`') {\\\\n        return 'Auerbach';\\\\n    }\\\\n    if (value === 'Voß') {\\\\n        return 'Voss';\\\\n    }\\\\n}\\\\nif (key === 'First Name') {\\\\n    if (value === 'Jörn Torsten') {\\\\n        return 'Jorn Torsten';\\\\n    }\\\\n}\\\"}\",\"{\\\"onBatch\\\":\\\"window.OmniGo.proMen = [\\\\n    'adam roberge'\\\\n];\\\\n\\\\nwindow.OmniGo.proWomen = [\\\\n    'whitney allison'\\\\n];\\\",\\\"onItem\\\":\\\"// Start Time\\\\nif (key === 'Start Time') {\\\\n    return null;\\\\n}\\\"}\",\"{\\\"onBatch\\\":\\\"\\\",\\\"onItem\\\":\\\"/* append Gender to class */\\\\nif (key === 'Class' && (value === 'Waffle' || value === 'Wafer' || value === 'Wanna')) {\\\\n    return value + (record['Gender'] ? ': ' + context.toMenWomen(context.toGenderBool(record['Gender'])) : '');\\\\n}\\\"}\",\"{\\\"onBatch\\\":\\\"\\\",\\\"onItem\\\":\\\"/* Assign final class name */\\\\nif (key === 'Class') {\\\\n    const classes = context.filterClasses(record.Gender, record.Birthday, record.Class);\\\\n    if (classes.length === 1) {\\\\n        return classes[0].className;\\\\n    }\\\\n    if (classes.length > 1) {\\\\n        // teams cause some confusion\\\\n        const teamCls = classes.find(cls => cls.className.indexOf('Teams') > -1);\\\\n        if (teamCls) {\\\\n            if (record.Class.indexOf('Team') > -1) {\\\\n                return teamCls.className;\\\\n            } else {\\\\n                const nonTeamClasses = classes.filter(cls => cls.className.indexOf('Team') === -1);\\\\n                if (nonTeamClasses.length === 1) {\\\\n                    return nonTeamClasses[0].className;\\\\n                }\\\\n            }\\\\n        }\\\\n        // mtb and ebike classes cause some confusion\\\\n        const eBikeCls = classes.find(cls => cls.className.indexOf('EBike') > -1);\\\\n        const mtbCls = classes.find(cls => cls.className.indexOf('MTB') > -1);\\\\n        if (mtbCls || eBikeCls) {\\\\n            if (record['Category Entered / Merchandise Ordered'].indexOf('MTB') > -1) {\\\\n                return mtbCls.className;\\\\n            }\\\\n            if (record['Category Entered / Merchandise Ordered'].indexOf('EBike') > -1){\\\\n                return eBikeCls.className;\\\\n            }\\\\n            const filteredClasses = classes.filter(cls => cls.className.indexOf('EBike') === -1 && cls.className.indexOf('MTB') === -1);\\\\n            if (filteredClasses.length === 1) {\\\\n                return filteredClasses[0].className;\\\\n            }\\\\n        }\\\\n        console.log('Unable to determine class', {record, classes, class: record['Class']});\\\\n        return record['Class'].split(':')[0] + ': UNKNOWN';\\\\n    }\\\\n}\\\"}\",\"{\\\"onBatch\\\":\\\"\\\",\\\"onItem\\\":\\\"/* Adjust start times a bit for certain classes */\\\\nif (key === 'Start Time') {\\\\n    const category = record['Attendee Select  Road Category'] || '';\\\\n    const cls = record['Class'].toLowerCase();\\\\n    const name = (record['First Name'] + ' ' + record['Last Name']).toLowerCase();\\\\n}\\\"}\",\"{\\\"onBatch\\\":\\\"window.OmniGo.bibErrors = [];\\\\n/* setup bib ranges */\\\\nwindow.OmniGo.bibs = {\\\\n    'waffle': {\\\\n        last: 0, \\\\n        ranges:'11-50,55-500'\\\\n    },\\\\n    'wafer': {\\\\n        last:0,\\\\n        ranges: '2000-2100,2387-2600',\\\\n    },\\\\n    'wanna': {\\\\n        last: 0,\\\\n        ranges: '3000-3050,3146-3200,3401-3500'\\\\n    }\\\\n};\\\\nwindow.OmniGo.assignedBibs = [];\\\\n\\\\n/* combine tandems */\\\\nconst reducedRecords = records.reduce((acc, cur) => {\\\\n  if (cur['Class'].indexOf('Tandem') > -1) {\\\\n    // is this the first team member?\\\\n    const otherTeamMemberIndex = acc.findIndex(r => r['Class'] === cur['Class'] && r['Team'] === cur['Team']);\\\\n    if (otherTeamMemberIndex > -1) {\\\\n      const firstTeamMember = acc[otherTeamMemberIndex];\\\\n      // we found another team member in the list, adjust the existing record\\\\n      firstTeamMember['First Name'] = firstTeamMember['First Name'] + ' ' + firstTeamMember['Last Name'] + ' and ' + cur['First Name'];\\\\n      firstTeamMember['Last Name'] = cur['Last Name'];\\\\n      firstTeamMember['Gender'] = cur['Gender'] === 'M' ? 'M' : firstTeamMember['Gender'];\\\\n    } else {\\\\n      // this is the first team member, add the record\\\\n      acc.push(cur);\\\\n    }\\\\n  } else {\\\\n    // not a tandem, add record\\\\n    acc.push(cur);\\\\n  }\\\\n  return acc;\\\\n}, []);\\\\n\\\\n/* sort by category */\\\\nconst sortedRecords = _.orderBy(reducedRecords, record => {\\\\n    const category = record['Custom: License Category '];\\\\n    if (!category) {\\\\n        return 7;\\\\n    }\\\\n    if (category === 'Pro') {\\\\n        return 1;\\\\n    }\\\\n    if (category === 1) {\\\\n        return 2;\\\\n    }\\\\n    if (category === 2) {\\\\n        return 3;\\\\n    }\\\\n    if (category === 3) {\\\\n        return 4;\\\\n    }\\\\n    if (category === 4) {\\\\n        return 5;\\\\n    }\\\\n    if (category === 5) {\\\\n        return 6;\\\\n    }\\\\n    return 7;\\\\n});\\\\nreturn sortedRecords;\\\",\\\"onItem\\\":\\\"const reserved = {\\\\n    'rebecca fahringer': 3,\\\\n    'nicholas roche': 4,\\\\n    'katerina nash': 5,\\\\n    'robert britton': 6,\\\\n    'cullen easter': 8,\\\\n    'amelia durst': 10,\\\\n    'nobody wants it':13,\\\\n    'derek betcher': 44,\\\\n    'michael van den ham': 51,\\\\n    'owen vermeulen': 52\\\\n};\\\\nconst reservedBibNumbers = Object.values(reserved);\\\\ncontext.existingBibs = context.existingBibs || [];\\\\nconst getNextBib = (bibConfig) => {\\\\n    const nextBib = context.getNextBib(bibConfig, window.OmniGo.assignedBibs, reservedBibNumbers, context.cancelledBibs, context.existingBibs);\\\\n    if (nextBib.err) {\\\\n        window.OmniGo.bibErrors.push(nextBib.err);\\\\n    };\\\\n    return nextBib.bib;\\\\n}\\\\n/*const getNextBib = (key) => {\\\\n    let bib = window.OmniGo.bibs[key].last > 0 ? window.OmniGo.bibs[key].last + 1 : window.OmniGo.bibs[key].min;\\\\n    while (!!window.OmniGo.assignedBibs[bib] || reservedBibNumbers.indexOf(bib) > -1 || context.cancelledBibs.indexOf(bib) > -1 || context.existingBibs.indexOf(bib) > -1) {\\\\n        bib++;\\\\n    }\\\\n    window.OmniGo.bibs[key].last = bib;\\\\n    window.OmniGo.assignedBibs[bib] = true;\\\\n    return bib;\\\\n};*/\\\\nif (key === 'Bib') {\\\\n    const category = record['Attendee Select  Road Category'] || '';\\\\n    if (record['Bib']) {\\\\n        const existingBib = parseInt(record['Bib']);\\\\n        window.OmniGo.assignedBibs[existingBib] = existingBib;\\\\n        return record['Bib'];\\\\n    }\\\\n    const reservedBib = reserved[(record['First Name'] + ' ' + record['Last Name']).toLowerCase()];\\\\n    if (reservedBib) {\\\\n        return reservedBib;\\\\n    }\\\\n    const cls = record['Class'].toLowerCase();\\\\n    const bibKeys = Object.keys(window.OmniGo.bibs);\\\\n    const bibKey = bibKeys.find(k => cls.indexOf(k) === 0);\\\\n    return getNextBib(window.OmniGo.bibs[bibKey]);\\\\n}\\\"}\"]",
  enabled: true,
  timezone: "America/Los_Angeles",
  options: {
    units: "metric",
    showLaps: false,
    bibRanges: {
      "1-1999": { color: "#FFFFFF", backgroundColor: "#000000" },
      "2000-2999": { color: "#FFFFFF", backgroundColor: "#49BEEC" },
      "3000-3999": { color: "#000000", backgroundColor: "#F8C808" },
    },
    distanceAliases: {
      "32.40 M": "Wanna",
      "67.30 M": "Wafer",
      "136.20 M": "Waffle",
    },
  },
  EventType: { id: "3", name: "Road Cycling" },
  User: {
    id: "1065b7d9-24e0-4223-a831-3a5d7eb26342",
    email: "tony@omnigoevents.com",
    firstName: "Tony",
    lastName: "Restuccia",
  },
  EventClasses: [
    {
      classWithPrefix: "Waffle: Pro Women",
      id: "5400",
      className: "Waffle: Pro Women",
      prefix: null,
      laps: 6,
      distance: "136.20",
      units: "M",
      wave: 2,
      listOrder: 10,
      startTS: "2023-05-28T14:00:08.365Z",
      finalTS: null,
      gender: 0,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      classWithPrefix: "Waffle: Women 18 and under",
      id: "5341",
      className: "Waffle: Women 18 and under",
      prefix: null,
      laps: 6,
      distance: "136.20",
      units: "M",
      wave: 2,
      listOrder: 11,
      startTS: "2023-05-28T14:00:08.365Z",
      finalTS: null,
      gender: 0,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      classWithPrefix: "Waffle: Women U23",
      id: "5345",
      className: "Waffle: Women U23",
      prefix: null,
      laps: 6,
      distance: "136.20",
      units: "M",
      wave: 2,
      listOrder: 12,
      startTS: "2023-05-28T14:00:08.365Z",
      finalTS: null,
      gender: 0,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      classWithPrefix: "Waffle: Women 23 to 34",
      id: "5364",
      className: "Waffle: Women 23 to 34",
      prefix: null,
      laps: 6,
      distance: "136.20",
      units: "M",
      wave: 2,
      listOrder: 13,
      startTS: "2023-05-28T14:00:08.365Z",
      finalTS: null,
      gender: 0,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      classWithPrefix: "Waffle: Women 35 to 44",
      id: "5363",
      className: "Waffle: Women 35 to 44",
      prefix: null,
      laps: 6,
      distance: "136.20",
      units: "M",
      wave: 2,
      listOrder: 14,
      startTS: "2023-05-28T14:00:08.365Z",
      finalTS: null,
      gender: 0,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      classWithPrefix: "Waffle: Women 45 to 54",
      id: "5326",
      className: "Waffle: Women 45 to 54",
      prefix: null,
      laps: 6,
      distance: "136.20",
      units: "M",
      wave: 2,
      listOrder: 15,
      startTS: "2023-05-28T14:00:08.365Z",
      finalTS: null,
      gender: 0,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      classWithPrefix: "Waffle: Women 55 to 64",
      id: "5344",
      className: "Waffle: Women 55 to 64",
      prefix: null,
      laps: 6,
      distance: "136.20",
      units: "M",
      wave: 2,
      listOrder: 16,
      startTS: "2023-05-28T14:00:08.365Z",
      finalTS: null,
      gender: 0,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      classWithPrefix: "Waffle: Women 65 to 69",
      id: "5340",
      className: "Waffle: Women 65 to 69",
      prefix: null,
      laps: 6,
      distance: "136.20",
      units: "M",
      wave: 2,
      listOrder: 17,
      startTS: "2023-05-28T14:00:08.365Z",
      finalTS: null,
      gender: 0,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      classWithPrefix: "Waffle: Women 70 Plus",
      id: "5343",
      className: "Waffle: Women 70 Plus",
      prefix: null,
      laps: 6,
      distance: "136.20",
      units: "M",
      wave: 2,
      listOrder: 18,
      startTS: "2023-05-28T14:00:08.365Z",
      finalTS: null,
      gender: 0,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      classWithPrefix: "Waffle: Pro Men",
      id: "5399",
      className: "Waffle: Pro Men",
      prefix: null,
      laps: 6,
      distance: "136.20",
      units: "M",
      wave: 1,
      listOrder: 30,
      startTS: "2023-05-28T14:00:08.365Z",
      finalTS: null,
      gender: 1,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      classWithPrefix: "Waffle: Men 18 and under",
      id: "5361",
      className: "Waffle: Men 18 and under",
      prefix: null,
      laps: 6,
      distance: "136.20",
      units: "M",
      wave: 1,
      listOrder: 31,
      startTS: "2023-05-28T14:00:08.365Z",
      finalTS: null,
      gender: 1,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      classWithPrefix: "Waffle: Men U23",
      id: "5357",
      className: "Waffle: Men U23",
      prefix: null,
      laps: 6,
      distance: "136.20",
      units: "M",
      wave: 1,
      listOrder: 32,
      startTS: "2023-05-28T14:00:08.365Z",
      finalTS: null,
      gender: 1,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      classWithPrefix: "Waffle: Men 23 to 34",
      id: "5356",
      className: "Waffle: Men 23 to 34",
      prefix: null,
      laps: 6,
      distance: "136.20",
      units: "M",
      wave: 1,
      listOrder: 33,
      startTS: "2023-05-28T14:00:08.365Z",
      finalTS: null,
      gender: 1,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      classWithPrefix: "Waffle: Men 35 to 44",
      id: "5365",
      className: "Waffle: Men 35 to 44",
      prefix: null,
      laps: 6,
      distance: "136.20",
      units: "M",
      wave: 1,
      listOrder: 34,
      startTS: "2023-05-28T14:00:08.365Z",
      finalTS: null,
      gender: 1,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      classWithPrefix: "Waffle: Men 45 to 54",
      id: "5342",
      className: "Waffle: Men 45 to 54",
      prefix: null,
      laps: 6,
      distance: "136.20",
      units: "M",
      wave: 1,
      listOrder: 35,
      startTS: "2023-05-28T14:00:08.365Z",
      finalTS: null,
      gender: 1,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      classWithPrefix: "Waffle: Men 55 to 64",
      id: "5359",
      className: "Waffle: Men 55 to 64",
      prefix: null,
      laps: 6,
      distance: "136.20",
      units: "M",
      wave: 1,
      listOrder: 36,
      startTS: "2023-05-28T14:00:08.365Z",
      finalTS: null,
      gender: 1,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      classWithPrefix: "Waffle: Men 65 to 69",
      id: "5358",
      className: "Waffle: Men 65 to 69",
      prefix: null,
      laps: 6,
      distance: "136.20",
      units: "M",
      wave: 1,
      listOrder: 37,
      startTS: "2023-05-28T14:00:08.365Z",
      finalTS: null,
      gender: 1,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      classWithPrefix: "Waffle: Men 70 Plus",
      id: "5360",
      className: "Waffle: Men 70 Plus",
      prefix: null,
      laps: 6,
      distance: "136.20",
      units: "M",
      wave: 1,
      listOrder: 38,
      startTS: "2023-05-28T14:00:08.365Z",
      finalTS: null,
      gender: 1,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      classWithPrefix: "Waffle: Tandem",
      id: "5362",
      className: "Waffle: Tandem",
      prefix: null,
      laps: 6,
      distance: "136.20",
      units: "M",
      wave: 1,
      listOrder: 39,
      startTS: "2023-05-28T14:00:08.365Z",
      finalTS: null,
      gender: -1,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      classWithPrefix: "Wafer: Women 18 and under",
      id: "5338",
      className: "Wafer: Women 18 and under",
      prefix: null,
      laps: 6,
      distance: "67.30",
      units: "M",
      wave: 3,
      listOrder: 50,
      startTS: "2023-05-28T14:14:59.597Z",
      finalTS: null,
      gender: 0,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      classWithPrefix: "Wafer: Women U23",
      id: "5378",
      className: "Wafer: Women U23",
      prefix: null,
      laps: 6,
      distance: "67.30",
      units: "M",
      wave: 3,
      listOrder: 51,
      startTS: "2023-05-28T14:14:59.597Z",
      finalTS: null,
      gender: 0,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      classWithPrefix: "Wafer: Women 23 to 34",
      id: "5367",
      className: "Wafer: Women 23 to 34",
      prefix: null,
      laps: 6,
      distance: "67.30",
      units: "M",
      wave: 3,
      listOrder: 52,
      startTS: "2023-05-28T14:14:59.597Z",
      finalTS: null,
      gender: 0,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      classWithPrefix: "Wafer: Women 35 to 44",
      id: "5346",
      className: "Wafer: Women 35 to 44",
      prefix: null,
      laps: 6,
      distance: "67.30",
      units: "M",
      wave: 3,
      listOrder: 53,
      startTS: "2023-05-28T14:14:59.597Z",
      finalTS: null,
      gender: 0,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      classWithPrefix: "Wafer: Women 45 to 54",
      id: "5375",
      className: "Wafer: Women 45 to 54",
      prefix: null,
      laps: 6,
      distance: "67.30",
      units: "M",
      wave: 3,
      listOrder: 54,
      startTS: "2023-05-28T14:14:59.597Z",
      finalTS: null,
      gender: 0,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      classWithPrefix: "Wafer: Women 55 to 64",
      id: "5377",
      className: "Wafer: Women 55 to 64",
      prefix: null,
      laps: 6,
      distance: "67.30",
      units: "M",
      wave: 3,
      listOrder: 55,
      startTS: "2023-05-28T14:14:59.597Z",
      finalTS: null,
      gender: 0,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      classWithPrefix: "Wafer: Women 65 to 69",
      id: "5374",
      className: "Wafer: Women 65 to 69",
      prefix: null,
      laps: 6,
      distance: "67.30",
      units: "M",
      wave: 3,
      listOrder: 56,
      startTS: "2023-05-28T14:14:59.597Z",
      finalTS: null,
      gender: 0,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      classWithPrefix: "Wafer: Women 70 Plus",
      id: "5368",
      className: "Wafer: Women 70 Plus",
      prefix: null,
      laps: 6,
      distance: "67.30",
      units: "M",
      wave: 3,
      listOrder: 57,
      startTS: "2023-05-28T14:14:59.597Z",
      finalTS: null,
      gender: 0,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      classWithPrefix: "Wafer: Men 18 and under",
      id: "5352",
      className: "Wafer: Men 18 and under",
      prefix: null,
      laps: 6,
      distance: "67.30",
      units: "M",
      wave: 3,
      listOrder: 61,
      startTS: "2023-05-28T14:14:59.597Z",
      finalTS: null,
      gender: 1,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      classWithPrefix: "Wafer: Men U23",
      id: "5355",
      className: "Wafer: Men U23",
      prefix: null,
      laps: 6,
      distance: "67.30",
      units: "M",
      wave: 3,
      listOrder: 62,
      startTS: "2023-05-28T14:14:59.597Z",
      finalTS: null,
      gender: 1,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      classWithPrefix: "Wafer: Men 23 to 34",
      id: "5339",
      className: "Wafer: Men 23 to 34",
      prefix: null,
      laps: 6,
      distance: "67.30",
      units: "M",
      wave: 3,
      listOrder: 63,
      startTS: "2023-05-28T14:14:59.597Z",
      finalTS: null,
      gender: 1,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      classWithPrefix: "Wafer: Men 35 to 44",
      id: "5333",
      className: "Wafer: Men 35 to 44",
      prefix: null,
      laps: 6,
      distance: "67.30",
      units: "M",
      wave: 3,
      listOrder: 64,
      startTS: "2023-05-28T14:14:59.597Z",
      finalTS: null,
      gender: 1,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      classWithPrefix: "Wafer: Men 45 to 54",
      id: "5330",
      className: "Wafer: Men 45 to 54",
      prefix: null,
      laps: 6,
      distance: "67.30",
      units: "M",
      wave: 3,
      listOrder: 65,
      startTS: "2023-05-28T14:14:59.597Z",
      finalTS: null,
      gender: 1,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      classWithPrefix: "Wafer: Men 55 to 64",
      id: "5332",
      className: "Wafer: Men 55 to 64",
      prefix: null,
      laps: 6,
      distance: "67.30",
      units: "M",
      wave: 3,
      listOrder: 66,
      startTS: "2023-05-28T14:14:59.597Z",
      finalTS: null,
      gender: 1,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      classWithPrefix: "Wafer: Men 65 to 69",
      id: "5349",
      className: "Wafer: Men 65 to 69",
      prefix: null,
      laps: 6,
      distance: "67.30",
      units: "M",
      wave: 3,
      listOrder: 67,
      startTS: "2023-05-28T14:14:59.597Z",
      finalTS: null,
      gender: 1,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      classWithPrefix: "Wafer: Men 70 Plus",
      id: "5372",
      className: "Wafer: Men 70 Plus",
      prefix: null,
      laps: 6,
      distance: "67.30",
      units: "M",
      wave: 3,
      listOrder: 68,
      startTS: "2023-05-28T14:14:59.597Z",
      finalTS: null,
      gender: 1,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      classWithPrefix: "Wafer: Tandem",
      id: "5370",
      className: "Wafer: Tandem",
      prefix: null,
      laps: 6,
      distance: "67.30",
      units: "M",
      wave: 3,
      listOrder: 90,
      startTS: "2023-05-28T14:14:59.597Z",
      finalTS: null,
      gender: -1,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      classWithPrefix: "Wafer: EBike",
      id: "5350",
      className: "Wafer: EBike",
      prefix: null,
      laps: 6,
      distance: "67.30",
      units: "M",
      wave: 3,
      listOrder: 91,
      startTS: "2023-05-28T14:14:59.597Z",
      finalTS: null,
      gender: -1,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      classWithPrefix: "Wafer: Unknown",
      id: "5379",
      className: "Wafer: Unknown",
      prefix: null,
      laps: 6,
      distance: "67.30",
      units: "M",
      wave: 3,
      listOrder: 95,
      startTS: "2023-05-28T14:14:59.597Z",
      finalTS: null,
      gender: -1,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      classWithPrefix: "Wanna: Women 18 and under",
      id: "5327",
      className: "Wanna: Women 18 and under",
      prefix: null,
      laps: 6,
      distance: "32.40",
      units: "M",
      wave: 3,
      listOrder: 101,
      startTS: "2023-05-28T14:14:59.597Z",
      finalTS: null,
      gender: 0,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      classWithPrefix: "Wanna: Women U23",
      id: "5329",
      className: "Wanna: Women U23",
      prefix: null,
      laps: 6,
      distance: "32.40",
      units: "M",
      wave: 3,
      listOrder: 102,
      startTS: "2023-05-28T14:14:59.597Z",
      finalTS: null,
      gender: 0,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      classWithPrefix: "Wanna: Women 23 to 34",
      id: "5351",
      className: "Wanna: Women 23 to 34",
      prefix: null,
      laps: 6,
      distance: "32.40",
      units: "M",
      wave: 3,
      listOrder: 103,
      startTS: "2023-05-28T14:14:59.597Z",
      finalTS: null,
      gender: 0,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      classWithPrefix: "Wanna: Women 35 to 44",
      id: "5371",
      className: "Wanna: Women 35 to 44",
      prefix: null,
      laps: 6,
      distance: "32.40",
      units: "M",
      wave: 3,
      listOrder: 104,
      startTS: "2023-05-28T14:14:59.597Z",
      finalTS: null,
      gender: 0,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      classWithPrefix: "Wanna: Women 45 to 54",
      id: "5336",
      className: "Wanna: Women 45 to 54",
      prefix: null,
      laps: 6,
      distance: "32.40",
      units: "M",
      wave: 3,
      listOrder: 105,
      startTS: "2023-05-28T14:14:59.597Z",
      finalTS: null,
      gender: 0,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      classWithPrefix: "Wanna: Women 55 to 64",
      id: "5347",
      className: "Wanna: Women 55 to 64",
      prefix: null,
      laps: 6,
      distance: "32.40",
      units: "M",
      wave: 3,
      listOrder: 106,
      startTS: "2023-05-28T14:14:59.597Z",
      finalTS: null,
      gender: 0,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      classWithPrefix: "Wanna: Women 65 to 69",
      id: "5369",
      className: "Wanna: Women 65 to 69",
      prefix: null,
      laps: 6,
      distance: "32.40",
      units: "M",
      wave: 3,
      listOrder: 107,
      startTS: "2023-05-28T14:14:59.597Z",
      finalTS: null,
      gender: 0,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      classWithPrefix: "Wanna: Women 70 Plus",
      id: "5376",
      className: "Wanna: Women 70 Plus",
      prefix: null,
      laps: 6,
      distance: "32.40",
      units: "M",
      wave: 3,
      listOrder: 108,
      startTS: "2023-05-28T14:14:59.597Z",
      finalTS: null,
      gender: 0,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      classWithPrefix: "Wanna: Men 18 and under",
      id: "5366",
      className: "Wanna: Men 18 and under",
      prefix: null,
      laps: 6,
      distance: "32.40",
      units: "M",
      wave: 3,
      listOrder: 111,
      startTS: "2023-05-28T14:14:59.597Z",
      finalTS: null,
      gender: 1,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      classWithPrefix: "Wanna: Men U23",
      id: "5348",
      className: "Wanna: Men U23",
      prefix: null,
      laps: 6,
      distance: "32.40",
      units: "M",
      wave: 3,
      listOrder: 112,
      startTS: "2023-05-28T14:14:59.597Z",
      finalTS: null,
      gender: 1,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      classWithPrefix: "Wanna: Men 23 to 34",
      id: "5353",
      className: "Wanna: Men 23 to 34",
      prefix: null,
      laps: 6,
      distance: "32.40",
      units: "M",
      wave: 3,
      listOrder: 113,
      startTS: "2023-05-28T14:14:59.597Z",
      finalTS: null,
      gender: 1,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      classWithPrefix: "Wanna: Men 35 to 44",
      id: "5335",
      className: "Wanna: Men 35 to 44",
      prefix: null,
      laps: 6,
      distance: "32.40",
      units: "M",
      wave: 3,
      listOrder: 114,
      startTS: "2023-05-28T14:14:59.597Z",
      finalTS: null,
      gender: 1,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      classWithPrefix: "Wanna: Men 45 to 54",
      id: "5337",
      className: "Wanna: Men 45 to 54",
      prefix: null,
      laps: 6,
      distance: "32.40",
      units: "M",
      wave: 3,
      listOrder: 115,
      startTS: "2023-05-28T14:14:59.597Z",
      finalTS: null,
      gender: 1,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      classWithPrefix: "Wanna: Men 55 to 64",
      id: "5334",
      className: "Wanna: Men 55 to 64",
      prefix: null,
      laps: 6,
      distance: "32.40",
      units: "M",
      wave: 3,
      listOrder: 116,
      startTS: "2023-05-28T14:14:59.597Z",
      finalTS: null,
      gender: 1,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      classWithPrefix: "Wanna: Men 65 to 69",
      id: "5328",
      className: "Wanna: Men 65 to 69",
      prefix: null,
      laps: 6,
      distance: "32.40",
      units: "M",
      wave: 3,
      listOrder: 117,
      startTS: "2023-05-28T14:14:59.597Z",
      finalTS: null,
      gender: 1,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      classWithPrefix: "Wanna: Men 70 Plus",
      id: "5331",
      className: "Wanna: Men 70 Plus",
      prefix: null,
      laps: 6,
      distance: "32.40",
      units: "M",
      wave: 3,
      listOrder: 118,
      startTS: "2023-05-28T14:14:59.597Z",
      finalTS: null,
      gender: 1,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      classWithPrefix: "Wanna: Tandem",
      id: "5354",
      className: "Wanna: Tandem",
      prefix: null,
      laps: 6,
      distance: "32.40",
      units: "M",
      wave: 3,
      listOrder: 130,
      startTS: "2023-05-28T14:14:59.597Z",
      finalTS: null,
      gender: -1,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      classWithPrefix: "Wanna: EBike",
      id: "5373",
      className: "Wanna: EBike",
      prefix: null,
      laps: 6,
      distance: "32.40",
      units: "M",
      wave: 3,
      listOrder: 131,
      startTS: "2023-05-28T14:14:59.597Z",
      finalTS: null,
      gender: -1,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
  ],
  EventLapAliases: [],
  checkpoints: [
    {
      id: "0429019d-6634-4e02-8281-1a406a5e4106",
      name: "Southern Loop",
      distance: "79.90",
      units: "M",
      options: {
        lap: 3,
        asLap: true,
        racerPassedCheckpoint: {
          body: "const isWaffle = racer.className.indexOf('Waffle') === 0; if (!isWaffle) {     return true; } const cp1 = '01adb4f1-fc6b-48f4-8bb4-d02cd0ad0520'; const cp2 = '02e6b0c9-d243-4b67-905d-e7925051d2c4'; const cp3 = '03560c69-9f31-4253-ba69-4e949c652338'; const previousCheckpointIds = [cp1, cp2]; const previousRequiredCheckpointIds = [...requiredCheckpoints.filter(c => previousCheckpointIds.indexOf(c.id) > -1).map(cp => cp.id), checkpoint.id]; const passedPreviousRequiredCheckpoints = previousRequiredCheckpointIds.every(requiredId => !!checkpointTimes.find(ct => ct.eventCheckpointId === requiredId)); const passedThisCheckpoint = !!checkpointTimes.find(ct => ct.eventCheckpointId === checkpoint.id); return passedPreviousRequiredCheckpoints && passedThisCheckpoint;",
          arguments: "racer, checkpoint, checkpointTimes, requiredCheckpoints",
        },
      },
      required: true,
      enabled: true,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      id: "01adb4f1-fc6b-48f4-8bb4-d02cd0ad0520",
      name: "Double D",
      distance: "17.90",
      units: "M",
      options: {
        lap: 1,
        asLap: true,
        racerPassedCheckpoint: {
          body: "return !!checkpointTimes.find(ct => ct.eventCheckpointId === checkpoint.id);",
          arguments: "racer, checkpoint, checkpointTimes, requiredCheckpoints",
        },
      },
      required: true,
      enabled: true,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      id: "02e6b0c9-d243-4b67-905d-e7925051d2c4",
      name: "Tunnel",
      distance: "31.90",
      units: "M",
      options: {
        lap: 2,
        asLap: true,
        racerPassedCheckpoint: {
          body: "const isWanna = racer.className.indexOf('Wanna') === 0; if (isWanna) {     return true; } const cp1 = '01adb4f1-fc6b-48f4-8bb4-d02cd0ad0520'; const previousCheckpointIds = [cp1]; const previousRequiredCheckpointIds = [...requiredCheckpoints.filter(c => previousCheckpointIds.indexOf(c.id) > -1).map(cp => cp.id), checkpoint.id]; const passedPreviousRequiredCheckpoints = previousRequiredCheckpointIds.every(requiredId => !!checkpointTimes.find(ct => ct.eventCheckpointId === requiredId)); const passedThisCheckpoint = !!checkpointTimes.find(ct => ct.eventCheckpointId === checkpoint.id); return passedPreviousRequiredCheckpoints && passedThisCheckpoint;",
          arguments: "racer, checkpoint, checkpointTimes, requiredCheckpoints",
        },
      },
      required: true,
      enabled: true,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      id: "0799774b-1f09-4627-ab4b-f6256633a45d",
      name: "Prevost Descent",
      distance: "134.10",
      units: "M",
      options: {
        lap: 5,
        asLap: true,
        distanceAliases: { "67.3 M": 65.22 },
        racerPassedCheckpoint: {
          body: "const isWanna = racer.className.indexOf('Wanna') === 0; const isWaffle = racer.className.indexOf('Waffle') === 0; if (isWanna) {     return true; } const cp1 = '01adb4f1-fc6b-48f4-8bb4-d02cd0ad0520'; const cp2 = '02e6b0c9-d243-4b67-905d-e7925051d2c4'; const cp3 = '03560c69-9f31-4253-ba69-4e949c652338'; const cp4 = '0429019d-6634-4e02-8281-1a406a5e4106'; const cp5 = '0599774b-1f09-4627-ab4b-f6256633a45d'; const cp6 = '0699774b-1f09-4627-ab4b-f6256633a45d'; const previousCheckpointIds = isWaffle ? [cp1, cp2, cp4, cp6] : [cp1, cp2, cp6]; const previousRequiredCheckpointIds = [...requiredCheckpoints.filter(c => previousCheckpointIds.indexOf(c.id) > -1).map(cp => cp.id), checkpoint.id]; const passedPreviousRequiredCheckpoints = previousRequiredCheckpointIds.every(requiredId => !!checkpointTimes.find(ct => ct.eventCheckpointId === requiredId)); const passedThisCheckpoint = !!checkpointTimes.find(ct => ct.eventCheckpointId === checkpoint.id); return passedPreviousRequiredCheckpoints && passedThisCheckpoint;",
          arguments: "racer, checkpoint, checkpointTimes, requiredCheckpoints",
        },
      },
      required: true,
      enabled: true,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      id: "0699774b-1f09-4627-ab4b-f6256633a45d",
      name: "Tunnel",
      distance: "120.50",
      units: "M",
      options: {
        lap: 4,
        asLap: true,
        distanceAliases: { "67.3 M": 51.6 },
        racerPassedCheckpoint: {
          body: "const isWanna = racer.className.indexOf('Wanna') === 0; const isWaffle = racer.className.indexOf('Waffle') === 0; if (isWanna) {    return true; } const cp1 = '01adb4f1-fc6b-48f4-8bb4-d02cd0ad0520'; const cp2 = '02e6b0c9-d243-4b67-905d-e7925051d2c4'; const cp3 = '03560c69-9f31-4253-ba69-4e949c652338'; const cp4 = '0429019d-6634-4e02-8281-1a406a5e4106'; const cp5 = '0599774b-1f09-4627-ab4b-f6256633a45d'; const previousCheckpointIds = isWaffle ? [cp1, cp2, cp4] : [cp1, cp2]; const previousRequiredCheckpointIds = [...requiredCheckpoints.filter(c => previousCheckpointIds.indexOf(c.id) > -1).map(cp => cp.id), checkpoint.id]; const passedPreviousRequiredCheckpoints = previousRequiredCheckpointIds.every(requiredId => !!checkpointTimes.find(ct => ct.eventCheckpointId === requiredId)); const passedThisCheckpoint = !!checkpointTimes.find(ct => ct.eventCheckpointId === checkpoint.id); return passedPreviousRequiredCheckpoints && passedThisCheckpoint;",
          arguments: "racer, checkpoint, checkpointTimes, requiredCheckpoints",
        },
      },
      required: true,
      enabled: true,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      id: "089cc152-9050-4672-b7c0-7124c343d29b",
      name: "Announcer's Line",
      distance: "136.10",
      units: "M",
      options: {
        showIfMissed: true,
        hideFromPublic: true,
        distanceAliases: { "32.4 M": 32.3, "67.3 M": 67.2 },
        racerPassedCheckpoint: {
          body: "const isWanna = racer.className.indexOf('Wanna') === 0; const isWaffle = racer.className.indexOf('Waffle') === 0; const cp1 = '01adb4f1-fc6b-48f4-8bb4-d02cd0ad0520'; const cp2 = '02e6b0c9-d243-4b67-905d-e7925051d2c4'; const cp3 = '03560c69-9f31-4253-ba69-4e949c652338'; const cp4 = '0429019d-6634-4e02-8281-1a406a5e4106'; const cp5 = '0599774b-1f09-4627-ab4b-f6256633a45d'; const cp6 = '0699774b-1f09-4627-ab4b-f6256633a45d'; const cp7 = '0799774b-1f09-4627-ab4b-f6256633a45d'; const previousCheckpointIds = isWanna ? [cp1] : isWaffle ? [cp1, cp2, cp4, cp6, cp7] : [cp1, cp2, cp6, cp7]; const previousRequiredCheckpointIds = [...requiredCheckpoints.filter(c => previousCheckpointIds.indexOf(c.id) > -1).map(cp => cp.id), checkpoint.id]; const passedPreviousRequiredCheckpoints = previousRequiredCheckpointIds.every(requiredId => !!checkpointTimes.find(ct => ct.eventCheckpointId === requiredId)); const passedThisCheckpoint = !!checkpointTimes.find(ct => ct.eventCheckpointId === checkpoint.id); return passedPreviousRequiredCheckpoints && passedThisCheckpoint;",
          arguments: "racer, checkpoint, checkpointTimes, requiredCheckpoints",
        },
      },
      required: false,
      enabled: true,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
  ],
  EventRoutes: [
    {
      id: "b77b19cf-6576-49b2-a298-587921dab1d0",
      distance: "136.20",
      polyline:
        "cnaiHjgcrV@oCPQD]J]l@a@VYRyABcB@gFC{FC{FAmCAmC}C@}C@_D@yB?yB@yB?qDFs@Mu@a@aBg@kAD{CpAeDCeDA_DCaDC_DAaDC_DC_DAaDCk@aFs@{C]cA_AgCgB_Ec@q@aBmBk@Ws@C_CN_CN_CPu@ViDfAq@Bw@Es@U_Am@}BcB}Ak@{Ak@cBmBiA}CIq@KcAe@qAo@s@}AuA_BwAcAoAyBaDeA_AcAi@qBMk@]s@sAq@kBQS{AwAkAq@}B[_CY}BM_CK}BMyAF_BH_BHcDCaDCy@Q{Ao@gAs@_B{AuAeAWiAsAgCcAiCWo@sAuBqAwBqBiCqBiCqBiCi@aAoAsF[}BSmDMqFGeAGaAg@kEg@kEs@sCsBaEk@yAk@aCk@aCo@mBeAiAeB[eBQeBSMSOc@?kApAgEx@iDn@gC~@cD~@aDb@}@hBeBjBeBpBsBpBsB`@k@d@mA`@sD`@qD^qDAaECaEA_EBqAPgBbAqFbAsF|@_Ez@_E|@_ELw@D}@BsAOwEMwEMwEIiCIgCBaBHqAP}@dAaEdAaEbAaEZ{@`AmAjBs@lBs@zB_AzB}@`Ag@nCaAz@[lCg@nDe@nDg@nDg@hBa@fB_@|Bi@`@ST_@?cGAcG?w@rDApDArDCtCAtCAnCAnCAnCApCKhAaAlAgCh@{Br@qCvByDd@g@rAcAt@a@fDq@hDs@lAJlBb@jB`@xBf@v@ZbAbA~@nCz@`Dx@jBv@dA~@f@~@LvAEz@K|AQtBKfANXL??Nc@Jw@@GEoAk@Gq@c@g@E[WM?a@AFi@BMl@Qx@@f@a@FG\\CV_BIm@Ga@OMg@Ja@s@SoBVCNKRO_@y@Aq@~@Cv@d@`@B^e@DETJd@b@JTXf@|@F~ACLa@b@Q`@WFF|@|@`@A\\CJA@LIJ?JJZLBBDIJ?TER?n@DBNHLd@`@JBUDq@IkCGiCDs@V_A\\w@x@}@vAuB\\y@Ps@N{A?y@Ss@_@USYF?ZDRON@d@fABXEXDJRBXc@L?HRN\\VWD[JEJv@J?VkAL?FbAKf@OTWRIb@Yv@S@SJGFq@|@aAj@u@j@U\\Y^wArAETRHVK`@CFDHDF^ANGHIp@AD]CQJUZGPKHCJAJCbAELKLGb@IfAERQPYPc@Py@F_A@{@VwBn@gBfAQZUb@WZy@|@WVOLM~@DB^Vr@h@??B@Ld@??FVFF??l@h@zArAnCfAdCRfCPfCRhAR~AZpAbApA`ArAlApAlArBMxA{A`CeCbByB`BwBbBwBFAvBm@vBm@p@Nv@\\vBxBz@|@hCpA`CXvA~@fAzAfAzAd@p@`BlC`DdBpC?vCuAFChA{Bp@oDhAgDfBaCdBcCZw@b@gAbAmBdAo@vC@tC@_@yCc@uDe@uDe@sD_@cE@uBbA_FfBqEhAqEf@aBVk@|@uB|@sBj@{Ch@}CR_DP_D`AcFbAeFXcAfAmDfAoDfAoDt@sEr@uEt@uE|@uD~@wD^mAvAwEvAwEhAqDjAoDnAcDnA{ETa@d@OfB?zAAdDH@xC?jBAt@?fD?dDGhCd@jDHfCD|AQxCSxCPnBvAvBxAvBf@h@LHt@V\\Dl@?`C[l@HZLn@b@z@tAhBvETf@b@t@vAmCrA_CZu@Ry@Js@H{AEqAUmE??[qFIu@Oo@w@qBMo@Kq@Co@?iBJmAXcBdAuDbAsDJaCeAqB`BuB`BuBt@c@`@AjAR??~Bd@~Bb@~Bb@^Rb@h@\\h@??jBxClBzCRj@Lp@Dj@@hF`@tCF???bDCfBDr@N??`AVFBH_AJc@HMPIH@l@NjA^VBj@Gf@Sn@Wn@Uz@?p@`@r@Xh@t@Hf@Oz@Q~@Gn@Xl@TVb@z@j@jAh@lAZn@X\\TNTJR@PCLMLa@JQL[NQd@{@l@gAb@{@x@qBr@eBf@qAf@qAb@q@d@STMXk@j@Mv@Cr@Ar@@r@Dl@?^Bl@Bz@@t@`@R\\f@t@v@a@nB}@^Nf@h@DDFC\\DT?t@OTGVS^g@HW@SVmEJe@JiABe@Hc@Xk@`@k@\\STARBRHVTRXBJBJ@RCZu@pCG`@?RHZFLLHl@APERIn@B`@Dp@L`@^V\\Z`@VLb@D?\\CXMl@AF_@@S`A[tAm@|BE@Ia@e@Pa@Pi@@QCUCS@OPGXItAUpBKb@Q@MNUXWd@CJCLO~AAAK\\WPMNMG??GEOJEd@@Pe@hABD??f@~@h@d@?@rA`BHXVl@Zt@\\hAr@V\\^A?_AI]hACBg@^c@v@AhBCbBP`BBdAC^SzBUdAq@t@}@\\Oh@Yp@Qr@AD?pAO`B?J@n@Ct@MjAIVQr@Tp@]vAEBUPQhAUHKh@Al@A@??UV??A@ME]?GKEkB???Go@ZQZ_@~@[v@Mb@G`@K`@?nG?lARzBCx@Ej@m@~BI~@B~@NbA`AdCB^QLe@@uA?eA{@g@iAUoAMgDMwAa@yCa@yCK_@q@qCs@qCoBqEgC{C_@_@]a@s@{Ai@wBYsA]g@YYYIu@?DpCDn@VvDTpBNhBH~AB`DCnGCrECpECrEEjBOfDOzAe@hDk@nC_@lBc@t@GBKJCL?TSjA}A|CUTa@p@c@`@i@v@Ex@v@~AdBrDbA~Bv@tBv@rBbAjDfAhEdA|DVdAz@zDx@lCx@lCj@tAtAzBnAnAnAnAdAl@`Ah@bD~AdDx@dDx@fA`@LFjCjBp@p@dCpDvAlCvAjCJPpAnATZZr@bAfD`AfDt@bBj@l@|@r@`BdA|@`Ar@hA|@~Ah@|Bh@bD\\n@b@dAvAlDvAlDjA|DRh@\\t@`@\\fAN`BBb@`@BPFJJF\\z@@bA@tC@vC?nDcB|AcB|Ag@d@mAfBmAdBcBtA}AdBaApBc@z@u@fEuAdBkBb@sApAaBdBaAhA[j@oB|CoB|CoB|CKRi@~@MJaBBgADeD?eD@gD?iB?iB?mCBmCBmCBqCFoCFw@G_As@M\\Y\\_B@_B?_D@_DB_D@_DB_D@_DB_D@_DBkCBkC@kC@kCBwC@ATgAVw@@c@DSk@KO]Ss@[}@m@w@a@sAY}@Gg@Im@Kw@_@IE[[kAyA_@o@_@u@Oc@y@aAM[EKBi@DCHOB]EUBWAGKQAOB}@Fw@@QF]?YHiAASGyABs@GUMWEQEu@BWQiAU]a@CC?G?]XSDGDSBKFSXe@b@Qd@_@t@KHMXEByAKm@Dc@HKF}@G_@Ua@OU]Kg@Do@CmBCsFFs@No@Rk@tBmCXi@L]VwA^qCuBUyAc@wAe@k@g@g@y@YYe@]i@MeA?cAFuCl@aBn@Hd@LfDFxADvEYtCYtC_@dCKz@[nAa@z@a@l@yA|COh@kArE{@tFMhCBjF@lF@jF@lFoBi@]]a@a@g@Q_@Bm@TcBXeBX}AAsB?qBAeA^i@^gCtC]`@yA~@aClCUj@]h@o@r@{A`A}A`Ai@j@gClDkB`BkB`BkBbBSXUZiAnCq@~@g@d@{CxAYVKXMhBO^sArAaBxBaBxBeCpBOTIz@AbEArF?rF@rF@nFBnF@pF@pFBrF@pFBpF@pEFjA~CA~CA~CA~CAjCAjCAhCAjCChDAfDAhDChC?jCAhC?jCAnC?lCA^l@A|A?xB@vB@~CB~C@`CJt@HHf@@?tAGd@KdACl@Kh@Of@M`@H?FbFDlARn@`AjBRnA?jC?jCL?hD?fD@hD?tC?vC@tC?vC?hC?hC@fC?dAzFl@fDr@nFLdF@pE@nE@pE?pF?rF?pF?pF?xE?bG@`G?bG?bGFtDBdA^~Ex@tEv@zBv@zB|AlC`BvB`BvBpBdCpBdCpBdCpBdClCbDjCdDlCdDjCdD|JjMP^h@v@v@bAx@bALP~@jAp@x@n@x@t@z@XZdDtD^RX\\hArA@V@NBFZs@DEFJLRJJNVV`@f@n@^b@Vn@?NEHy@kA_BuBuBiC}BsC}BsC_BoB?wA?eG?eG@gG?eGFuDAw@CeDAgDAkF?mF?kFAmF?uFAwF?uFAwF@mD@mD@_GEqA@u@Ns@HUj@q@ZCnDCnDCzCA|CAzCChCAhCAfCAlBCjBCbDIbDIbDIx@Kl@DFPLHPCJOfAo@jAi@lBw@lBw@DdE@fAR[RQrAkBrAiBvAeBpBmBpAs@f@[r@g@NKv@hAtC`Cz@d@FBJYLOj@HNG^{@LL|@v@TJXFh@Gl@XZBJCvAkAt@eAnAiBZ]Tw@VSDQFIb@[N[VY\\e@l@iAp@{A\\k@|@bBlAjDNb@Jb@PjABlDUhFUjFObCW|DKhCD|C`@fDfA~DrArDh@fCH\\j@fFj@dFl@dFj@fFf@bFT~At@hFr@hFf@jEH~@@`AOnEQpEGZ[zA{@hD}@hDOz@GpAB~BZvCb@`Bn@jAl@jAlBfDt@pAt@tB`AjD`AvD`AxDjA`FhAbFx@lEdAnFbAnFbApFbAnF?lFAvF?vF?vFEnDCnDZfBdA`DZ`AZtAf@hEd@hEd@nFd@pFf@pF`@vEPz@x@jBNf@Ft@W~DJhAL`@dAlAXh@Ld@@lCl@xD?z@\\v@TXNj@J`AFrADhE[rBA`@F`Ax@nC`AtB`AtBtBpALXJpA?P?xADb@\\~@Hl@NlEv@hEb@fBL~ExBN`@Pd@HLLN^L|@JZPV\\Pd@Nb@Xt@r@b@r@Tr@l@`EDn@FZh@p@jBpAT`@Lb@BtBBjEd@~AZj@Zx@ZrATtAZrDN~@Rj@T^XZz@`@j@h@Nd@DvA?jAUtEDdAR`Aj@vALfAAbAMxA?lAFnAb@tD`@tD\\rCh@zFLtCDbDDdDBdF@fFDd@Ld@`B`EDLjAhFT|ATxCFrBA|@Or@a@|@a@xAe@xD_@|Fo@zA[`@s@d@g@n@[l@a@dB[pBWtDWvDK|@m@zByAhDyAhDe@tFe@rF?TDfBN~A\\zE?xBItBBxBT~ET~EHd@Dp@Ap@e@dCShCk@vDAdCUxASf@m@f@gBVgBV[AUM}AqAc@UuAUYJ_CdBeBlBw@lAu@tAmAtCq@~Bo@xBUReDv@eDv@q@DWHo@`AeAxCc@x@Ij@E|@BnA\\bD\\bDPx@B~B@nBR~CP|C@h@SxD@pBV|CT|CV`F?j@B|DB|D@zD~AI~AK~B?|@LrBRrBPh@LNBl@Z`ArAPj@Hj@BpCAjGAhG?jGAvAGzFIzFIp@Qb@aAvAcAt@mBv@_CXaDD_A@mAJcCn@uBbAsBbAuBbAw@Z{Al@}Aj@{C|@k@Be@I_@[Yc@W}@KaABeEGsFCi@Ig@O[a@m@c@a@yAgAuCi@m@Hw@ToAhA[b@Yb@wB~Di@vAuAhE}@dBoCzCoCzC_@f@o@nAaAfCmAdE[x@a@b@m@~Do@|Do@~Dq@zCq@zCmA|Du@~C_@|B]nD[nDEfA^vD^bB`B`DzAvB~Bx@nCd@pCb@pCb@|@Vf@^d@j@rAxErAvErAxErAxErAxEd@vCI`EMfCOfCSjDQjDGjBHrAd@~@x@n@~@lBRv@DfAC`Ao@fBKVaB~EY`BEzAJjBR~@hBjDp@bBNxAClBM`Bg@nCg@nCGp@Ev@@nCR~Bd@lCbAI`AMPIv@[NU`@UVKd@MAIU{FWsECc@EqC@m@NwAd@eCdA_EdAaEz@mD|@mDz@mDxA}E~AqE|AqEvAkEvAkEtAkEvAmEvAkExAsEzAuExAsEhAsDhAqDfAqDhAqDlAoFV{An@eE^iDPgCPuDRuDN}DJmCLkCFwAT_FRaFT_FT_FRoCXsCVwBXeBt@cEv@eEh@gE`@sD`@sDf@sFJaBNqFNoFNqFLkFJmFLmFLkFJmFLkFLmFH{CFs@PcAZy@Zm@`@g@b@[|Am@zAm@fAk@r@}@n@gAj@uAb@qBX_Cb@eFb@cF`@cFb@cFXuCZuC`@aF`@}E`@_F`@}Eb@_FNiAT_AV{@b@iAl@gA`@aA^aA\\yA~@cFp@yEp@wEp@yEh@yEBiACmAe@}EIaBCgA?yCLgB^sC^uCFqBEiBOoA_@cEAgBDcBf@_D`AqF`AsF~@kFZeC`@uFb@uF`@sF`@uF`@uF`@sFb@uF`@uF`@sF^wE\\wE^yE^wE\\wEPyDC}AIcAMw@Sw@]s@g@o@i@_@}Ac@mBMm@Ye@]c@g@k@aA]iAo@gDy@{CI]Y{A]yCg@eFg@eF]eEQmDEeBFeFNiGLyCJwCHkECSCWUYQy@CkAJgDCMMc@o@i@SeAHiBF_AEm@Na@BQN@TIJQNq@LKF?J?h@RHeDFiBHaDHaD\\oFNcB^sCx@wFx@uFx@uFx@uFz@wFx@uFx@uFv@mFx@mFx@kFv@mFr@qEr@qEp@qEr@qEp@qEl@kCr@wBz@sBnAmBnAkBpBcCpBaCnBcCpBaCQeCC{@@y@H}A^eBDe@@e@Cm@Ik@Qk@Uk@Ja@zA}ExA_FzA}EJ[BILa@pAgEpAgEuBk@wBi@yCyAgAiAcAs@Q[IEa@Dk@XiCWmACi@Pe@X{AxAa@Vq@@YIk@oAc@a@w@Eg@Mk@a@m@{@s@{AyAsEYi@cB}Ca@g@uBwAg@e@w@_Ae@gA{@uCuAyDd@aBPqBB}DB{D\\qFKoC[_DAQgA}DiA}DgA}DgA_E]oC_@mE]mEi@}Ci@}CSyAa@yEE}@CeA?kF?mFEeBMyACs@DqAPoDFkFEaB_@cFSoAm@qCmAsFoAsFe@}AwAiD_@u@OYY]a@Kg@La@Ne@Ai@YYo@g@eBkAoFIoAAuFIiCQ{DQyDI{ECmERmFPmF]gDCyBHgCNcCbBgC`BgCbBiCrAmCn@aBh@{Bj@yBJcAAi@|AwAnAgBnAy@lBmBpAkBrBuDpBuDr@{AjAcBnAoAp@e@nAg@p@OZBd@Pt@t@z@`@`AVhALrBc@\\B`C`ArCn@rCl@pCn@zAv@h@v@hArCFNb@j@NJTPnCrAvBdAvBfAvBdAp@VpDNhBXfAb@r@b@nBlBr@h@x@L|BEzBCr@Kp@[t@w@vAyC`A}@x@a@h@IjCXzC?^Id@c@Xg@nA{CfBgEhBgErAgDrAgDrAgDtAeDrA}CtA}CtA}ChAeCfAeCzA}CzA}CzA}Cr@mBb@cCTuBBgBAuCCuCGeEEcEGeE?kDJ_BRgAlA_DjA}CN_@Fe@FsFAmAC{@I[sA}Bg@}@]{@So@eAkFc@uAOcAAaABo@Fa@`@_BTeBPwEPuEZcBHs@@_AA{@E]k@eCk@gCEcEdCcDbCcDhCaDbAgCbAeCx@{Cv@{CZyAd@_Cd@mDNq@`BgCRu@h@kEh@iEj@yCl@yCRmBZwFZwFPiFPiFpDApDCpDCtB?vBAlBBf@@zBBzBD|BBfCJfCL|BIpBBhCAfCAhCAzCAzCCzCAzCAxCA`@D`@j@Xn@`@VZBv@q@n@{@H]fA}C|@sCLe@D]LeCH_A`@yA|AsD~@_A\\A^B`ACdAg@L]Hg@?cAB{AEmCBg@Ze@v@c@~@]v@y@TcAf@yB^k@|Au@dAaAbBu@pAy@rAy@tB}CNqA\\}Ah@{@jAqAlAoApCkCbB}Az@YtAoB[qD{@_CKw@B]i@[c@Ek@Si@[o@m@m@mASs@g@aCy@cC_@{@Oe@y@aDOiACq@OsA_@mBM{@i@oFE]@}@Tm@rBmCjAiAjCcDjCaDbB{CbBeBbBcBLYp@yAj@q@p@_@lAc@jAcAvBwCtBuCvAiCvAkCvAiCpAuArAuANc@B[d@o@~@}@jAeAvByA\\W|Ay@jBgA~@w@lB{@p@c@AMfAe@XIrBFDDpAKBAp@JBJPJFAbCg@zBQVAb@DnCrBrAP|ATn@T`DV`@Cj@a@lAyAb@Sf@ER@b@~AF`@VfAJz@BfAFv@NpD?d@CfADlAElAIv@AXD|@EXQ`@STKTANGn@mAjCCNOxBGd@]~AIx@GzBHrCAZO~@An@Gb@Gn@Ch@GZ@fCId@CfCQjAI|@C|@?d@P`B@j@Hv@d@nBZrABlB@l@NlCCpBDVRd@jApB`@f@b@XTTFRDl@FPd@j@DP@PAp@GXOh@AH?HF^Vj@@lAJrCZvBDpAA|A?PDt@Kz@^nDEXS`@_BdCAZBhAa@xBj@hBOvA?`Ad@nBH\\a@tAJX[h@Ah@Fh@ZZx@]Va@f@B~@mD|@kD`@u@tAqBx@mAdBcDfBcDdBcD`BiC`BkCf@w@xAuCxAuCdAwBdAwB~@y@^OT?p@LtAHj@Dn@Jh@AdAk@|@cA~ANjAaA`Av@bC`APF~@Lj@EXAb@Dr@b@fBrBr@d@b@Jp@?bCq@z@GdAFfAb@XN\\\\tAl@`Al@\\Nd@J`AA`Ac@t@Sl@Ez@GHGXAZDx@`@l@r@jCj@p@P\\BxAAfAYjA]tBQrBOzAURB\\BpBc@t@Op@SRK`B]RK\\Gn@GrCk@p@Mb@?RIDGKON_@LQBCPNhC@jC?jC@fDBhD@fDBf@?|BG|BG|BG?mEvAGrBMrBKh@BlDn@lDl@lDn@n@D~@BjACt@P~An@~An@NF|B`BrBjAv@xAj@dBd@x@jA~AlA`BhA`A~@`AnBjETt@`@rCFRL`@b@|@d@l@j@hBXzBRx@Th@b@\\b@PhADfCAfCAfCA`CA~BAd@EbD{AhCeA~Bq@\\Ej@FxAVxAXr@Lt@CjAStAe@n@]dBAh@Qx@e@vAqA\\o@f@{AdAkBrByBlBgAnBgAnBgAr@c@j@O|B]|As@zAu@v@s@nAyBp@u@p@e@bAc@`CW`@Bv@FpBf@h@FpAEbAc@nCs@zBMj@DdBv@jAXnAv@T\\v@r@d@VfBClCUxALl@TfAD~@ElD\\|BQ~BQxA_@v@Ct@Oj@CpBk@bA[~B_B|BaBbAeD`AeD`BkC`@_@^OTAlCLl@Gb@UdBqAZKtAOv@Ql@Eb@Cl@Wt@s@PALF^d@TNb@Dx@ArBa@bDgAzB[pAFhAKrCi@x@CtBDnABn@Lr@ZnBvA\\JhBc@pB}@nB{@n@QxBOr@Y~A{CJUz@y@pCsApCqAfAu@vBwBxBwBfAyAdA{Ax@uBX_BNuDLi@Zq@hB_CnA}BbAaAz@e@tCc@vCc@tCe@p@YXWR_@ZiAn@yDLa@R[HMPOZMbDUdDUhAXfAj@XB\\EtAk@tAm@jCcBpB{ApB{A~@aArAqApAsAXQ`@E|BcA|BaAzBaA~@iA~@cBbAwB|@cCv@uAj@uA~A_FRqA\\}Cn@aDLwABu@@u@J}@j@aDDy@@iC?iCFoANaARq@~@_B`AaBz@_C`A}DbA}Dp@mDn@kDt@zFVx@jAzBjAzBZ|@Nv@F~@BlB]`G@|@B`@PvB@fAMnAq@|Bq@~BUjBE~@@dAL`AVx@\\l@`@^j@NbD@dD@fCB`@Hd@VpB`CDGFQFAF@z@p@zAh@p@ZfADzBSh@LHABCVeBOsA@oAD_@@_BCq@Bw@@eAIaAGuC?mA@u@Ls@FwAEaBGe@AY?oBBQFQj@cA@M?wAB{@f@Al@IjCIb@@zAb@v@CbAYX@PFPRN\\v@|DDHH@JKjAgDn@eCNs@NmCNmCEgABmBGaAWsAA_@B_@t@kBHa@BkCB[r@wBrAwCZaAP_ADk@Ae@Mk@Wm@s@gAI_@MmAOqAIoAQuF@c@Fa@h@wBz@sD\\o@NSRMHMRg@V{@\\{@ZoAn@_Ax@wBTa@r@aAJ[TmADGL@T`@LPdAt@`@?h@Z\\DHHNP@J]j@CTBFj@ZRV~@l@JAf@URBPTJb@HvABLRT\\FXMjAUnAm@hAWNENJZl@HHPF\\C\\g@PEb@HlBOZHdABXCj@SNAz@^^@dBEj@_@JAdABHBVTF@hBa@fANT?^OLCLFTZV@REZEz@CVMRCn@Tf@GR@dCz@b@FZE`@h@NLR@x@Ih@QTK\\c@nAy@`@c@x@a@LEd@A^IVB^GJAPBZTjA?h@B\\Jp@CbAWd@Bf@Mb@?h@Bd@LDHRFg@lCIj@Wx@c@j@i@`@i@NcBFe@L{BtA{BtAiA~@w@~@uBzCsBzCcBjCqAtCqAtCqAtCk@`Ay@`AiAt@aAZaALu@CQ?oAYmB}@kB}@u@Uo@Cg@Hg@V]Zg@p@m@f@e@Nk@FyBQw@?i@Li@^]d@iAzBiAzB_B|Ck@|@m@f@iBx@k@n@sB~D}AxB}AxB}AxBgAdCgAfCaAtA]ZkCbCmC`Cs@f@w@Pi@Dy@GgBk@u@Iw@?}@Nw@^q@f@m@x@m@lA_@rASnAM|AAtAFvAh@vDHnAEfAUbBo@YoCoAc@CsBPcAAu@Y_C}@]UYWCLWt@VR?R?\\DXZXn@f@n@`@~Av@|Av@XH^^FP@b@AROVMLq@Vk@^SVgA~@aA`@IDY?OHYx@SjBA\\SJ[@SHEJG`@OVKZIJKlAG\\MZA`@EDQCW@EFAFBHFL\\VHF@H?HCDi@AQCa@JYCa@HKCEGG?IHM`@c@T[`@ITGT?N@j@LTBZCX@TEXIRGb@e@HABSXMHy@LGJGRc@`C@bBDPj@p@HL@J?PAJIP_A|@OTETq@j@SN]TIBi@d@MFa@@[Je@@GBSTSNKTGR?RDRLZ?XAPSp@EXE~AMn@IlA[tAS\\GVAN@j@K`@W^K\\MTc@h@S^]`AKPGLI`@Yf@YVKNYPg@l@mAn@YHe@BqAf@qArAu@t@WPUD_@@c@GWMg@CS@g@Bm@Cu@c@}Aq@SESBa@NoAd@qA\\o@d@e@Ls@b@cAdASHo@HMEg@o@USOGQAIBa@j@w@Xk@JcAASHQLOXk@vAk@hBs@zAaBfCUVq@h@ORMj@?lAETORSR[Nc@HsCAOHq@h@c@l@EL?HBDH@l@OR@LDHHDPDh@ALSb@[l@mB~CSVy@`@KLOz@MZYf@i@`@s@XUTENEfACn@DnDy@FeB@cAE]D\\XdAb@PNKNo@@qAH_@BeAb@q@h@eAbA{A~CuA`EmAnCm@jBK\\mAvBiCrBwCrAaCjB_Ab@o@V{AVcCUmBc@cB?eCNmBZeBL{ADmAW{AcAyAaAqCoBoCoByB}@eBc@aCo@cCo@aCo@oCg@_@FsATwB~@cC~AeC~AcC~AwCjBwAx@uAx@gBtAgBhCwA~BqB`DqBbDqB`DqBbDeBlB_Ah@kCvAiCxAwCfBkATaBFi@EqAKkDq@kDs@eC]iADi@PyC`AiAl@}BxBeBvBeBxBmA~AmA`BiAr@yC`BwBJoCMgD]]A{@FwBd@mBj@}Ax@q@Xg@RwAZaBFwBQyBSyBQs@GgBFeBFuA\\gDtAeDvAqBx@qBz@qBx@oBn@qBn@kAXy@?]Ay@?cAI{@[iBi@eDkAeDsAmBo@iB_@iB]wA?y@Na@JgBj@}AnA}AbBw@nAe@bAs@tCi@hDQ`BWbCUbCQvAc@vEe@`De@bBi@pAeBlCeAtA{@n@g@^}CvAwC~@wC~@_D~@}C|@kBr@kBr@{A`@yA`@y@h@e@ZeAfAaBhCcBhCMTcAdCs@zBk@nCk@zDQ~AMzCGz@@hC?jCE~CKhBc@nCqAlEw@rBi@~As@zCMbBGzBAjAJlB`@jCf@bCRzAJlAFlB@rBOdCQdCc@|Ce@~Cs@xEq@xEs@vEi@~CQ|CDtARfFAfBIdBSzAw@~DKjAo@fDaBzD{AvAiBxAkBzAiBxAcB|AiBxA{B|AeCjBw@~@_BvBaAvBw@r@sAd@iAJcAMc@U]ScAoAcBqCaBsCmAmB_AiBaAkB]oAqAiCoAiCo@sAiAcBm@k@o@_@aB]c@C[@[B}AXe@Zs@h@yAfBo@x@cA|@oBjAmBjAeBjAcBjAi@\\{@fAq@hAa@z@cAtDcAtDq@~Bq@~Bo@nBkAtBkAhAOHs@`@wBv@yBt@wBt@mBf@kBh@m@DcCPcCNaCPw@Xs@`@m@x@w@hB{@pEy@rE{@~E_@bBg@|Am@|As@`By@pAgArBkBjDgB`EcA~CeA`D}A|D{@pCy@pCwAvEcAfCeAvBiBhCo@`@s@Ty@JaCFg@GsBUuBUkBK{AHyAH{Bj@sAZw@^uC`BuC`BwC~AmC|AoCzAmCzAoC|AgCvAgCvAgCvA_BlA}AjAQJSJ}CdB{CdB}CdB{CbByAv@{Bl@sBAiBEeDo@yAU{ASyBKoALeBp@_CxA_BzA}AzAqAfAyAtAiAl@aA`@m@JgA?WIWI_B{@sAiAuAiAiBuAmAe@wAY_AIs@BgAPy@\\g@^{BtAyBtAwChBeCpBeB~A_B|BqArBaBlCaBnCeBnDiBlEiBlEiBlEiB~DkB|DkB~DiB|DkB~Dy@vA{@`Bo@v@_Ar@qAb@s@Jg@AgAQeCc@aAGs@Bm@LcAZuAx@{AhAk@fAyApCwAlBq@fAu@rBu@pBuAbEwA`EaAnBqAfBoAdBuBjCwBjCuBjCuBjC{BpC{BrCMNkB`CkB~BOP{ApByApBeBrBeBtBcBrBgAhAe@f@s@~@m@x@kC~CkC`DkC~CkC`DoAjBoAlB{@rBs@vBm@jCq@nEq@lEq@lEs@lEw@jFw@hFy@hFw@jFw@hFw@fFu@fFu@fFw@fFu@fFw@fFg@dDe@fD_@rCObB]nFE~AG`CKxDKvDUISIS?MJQt@ILUHOAEZMVB`@@JQhDF\\Jf@n@h@Pp@EnAEvABjAPx@TXFj@GvCMrDMpDOhGGdFDdBPlDXpDh@nFh@nF\\xCXzAbAxDn@fD\\hAj@`Ab@f@d@\\f@TrBP|Ab@h@^f@n@\\r@Rv@Lv@HbAB|AQxDc@tFa@vFc@tFa@jFa@hF_@jFa@hFa@jF_@dF_@bF_@bF_@dF_@bF_@dFQtAIn@aApFaAnF_AnFg@~CEbB@fB^bENnADhBE`BAN_@tC_@rCMfB?xCBfAH`Bd@|EBlAC`Ai@`Fc@~Ce@|Ce@dDe@fD_AbF]xA_@`Aa@`Am@fA{@dCU~@OhAYfDe@lFc@jFc@lFc@lF[tCYtCg@zFa@zEa@zEa@|EY~Bc@pBk@tAo@fAs@|@gAj@{Al@}Al@c@ZY\\c@v@[x@QbAGr@QpFMjGMjGOhGMjGMzFMzFOpFOnFOpFK`B_@~Da@|Di@|Ei@fEw@dEu@bEYdBWvBYrCSnCU~EU~ES`FU~EGvAQxDOzDQzDMfCMhCQfC_@hDo@dEWzAmAnFgAnDgApDiAnDyAtEyAtE{ArEyAtE{ArEyAtE{ArEyAtE{@hC}ApE_BpEyA|EkAxEmAxEkAxEm@~Bm@|Be@dCOvAAl@DpCZvFTzF@He@LWJa@TOTiAd@aALcAHe@mCEi@MuAAoCLiBf@oCf@oCLaBBmBOyA}@wB}AwCS_AKkBD{AXaB`B_FJWn@gBBaAEgASw@_AmB{@u@c@y@IsAFkBTmEVkETmEHaEe@wCeAsDwAcFuAaFwAcFwAaFe@k@g@_@gAYmCc@mCc@mCc@}Ai@a@O{AwBaBaD_@cB_@wDDgAZoD\\oD^}Bt@_DlA}Dn@uCr@aDn@_En@}Dl@_EcAm@}BwB_CaD_CcDm@q@uA[aDwA_@_@Wk@s@oCs@qCyA{CoAmC]_@c@OkBY_@Wa@g@aAgBcAgBi@g@Uv@cBtCaBvC@wELeEJeELcENeGPeGNeGNeGPeGNeG?}F?}FA_G?}F?}FA}FC_AW}FU{FW}FU}FKyEKyEDyFVuEVsEl@yEj@yEl@yEj@yEj@yEb@mDb@kDEqFGqFEoFp@qFn@oF^yD^wD^yDi@_FqAkDEKyA}B{A{Bm@oBa@uEc@sEc@uEm@aBiCoCiCqCqAsA{@{B{@}B{@yDi@{Eg@{Ei@}Ei@{EOkA?E_@kC_@kCo@qEo@qEo@qEa@cDa@cDk@yEk@wEm@yEk@wEs@aCq@_Cs@_Ca@cD_@aDDaFLo@MWAa@@QNiAZkAXs@ZeA\\{@\\mATmASy@?e@HaBZ_Bd@qBr@oEj@yCp@kDAACa@M[QXCDSVGHSTYRMFUNKDA?MBG?I?C???e@CQCEAKCWEWCKCWCo@G??Mo@k@wC_AsEUkBIoC@mBHqKFmKHoKH}KH_LH}KBoDBsF@[DmG@mBFqK@gCBwCBsBBuA@}AJ{EFkC@oD@wA@yD?UDeE@i@BeE@uA?oA?iAAw@EoAC[IaBk@uEW_BYgAEQQk@c@cAYo@gAoBMMe@kBaAoA_AuAm@tAO_A`AlAFM|AjBn@z@Vr@|@lBXn@`@bABFN`@\\vAXxAl@tERtCJp@@v@?xCAtACdECrCCzA?TCpGAnDKlEGxCA|AGhECvCC|EGhLEdF?f@EnGKfMQdWQfWOrUDbABjARfB`AvEx@fE??a@Qa@OiAe@cA_@a@Qc@OUKoAe@cAa@a@Qa@Oi@S@Gu@[wCk@}AE}AC{BR}BR}ANyASyASmCEmCCaBCaBCaBEaBGs@R]bAAfBLjFB|DB~DAzDC|DWpDWpDWpDCdBAt@LtDJtDM`Ce@fA}@hAsBvAuBxAeAz@cAfA{@pB_@pBEt@GdBDrDU?uB@uBB_ATk@h@cArBiAzAkA~AkA~AsA~A{@f@k@T_DT_AR_@Nc@`@{@v@mBzAkBxA_CdA_B\\_B^cCh@qARaDFcDHqAS_Ci@u@u@aAw@a@w@{@kEq@cA}@q@k@E_@LQFm@t@q@f@aA^}@Nq@KaAo@s@s@sAu@mAScCeAgAQgCIgCIiC[qAc@}@m@yByBsAeCkAkBo@o@}@a@kCQiBa@iA[MGuBiA_Bu@uAo@yCgByCgBa@o@_@aAQcAOwA?YN}@`@aBXq@r@qAdA_Bp@gBRmAXmCNgCDuCd@aEf@aEL{@ViA`AmCl@sBLqAIeCQ}CDgDBiDOmBUoAcAiD[iBk@sEYgDy@aEaAmCc@w@cCeDu@eAeAOgBNaDf@sBJwCa@iBcAiCcBmAiBwAiBs@YkCeAq@c@cAiA[e@y@q@uAWm@s@Mu@OwB{@}DGq@FaB[qBiBaCQiCSkCJkCJkCp@_EhBPfBNxAVzBTjALnA\\~@Fd@SVUjBuD|@sATQ`@CpADn@Gf@Wd@_@h@o@rAgChBkC^]hBi@nAi@vA_AvBs@\\GdB@fBBRErAg@z@Wj@AXFxAl@HF\\?ZGlBeAREd@?ZH`CtA|@VnBPpDL\\C\\MvBgAtBgAvBeAxA{@xAy@lA{AnAyAlAqAlAqA`@g@`AkB`AkBNe@h@mCHu@?gAFeBBoBEmDKgAs@oEu@mEk@oCSiASmB_@uACi@?a@HgBC]SmA[gAIYa@}@[sA[yBKe@w@aAk@e@u@{@QO}As@uA{@SYaAm@y@GQIU]sAo@u@m@YM_@EkA]gAm@s@Ku@UMIe@_Ak@y@[Oe@_@{@a@y@Q_Bk@WK_@]u@Ww@]mBsA]_@qAgAWK}@SWQu@_AIWAUDc@^c@l@_@FGJMRq@BSCwAMi@}@cBi@Yg@M[A[N_@XOBu@?iAOa@CmAJy@EeA?yBTs@?mAJi@A[B{A]kA_@e@UYG_@Bq@Iw@m@ICM@s@\\OFg@Bn@aBf@aAPu@Jy@Pw@l@uAbAcAj@o@dAcBzA_B~AkAlA{AdAwAj@_@`@OpB_@h@c@d@Ob@CzA?zA?~CHbANh@RRAJM@[IY[]]k@}@}Au@_AoAm@s@g@oAm@w@s@a@i@Qe@Eg@@m@Pc@b@Ur@KtB@jB]dAC`C\\`BXpCD|ARlCTbB`@ZMLRVL\\v@d@Tj@b@\\XjAj@lAz@rBb@tBd@dB`A\\_@PKv@UhAk@fDw@`CU`AGn@@hC]v@?r@JdAf@d@JN?TIVQXMvCQr@Ot@Ox@GnAQxB@lAHbAOPK`@i@LWZcBD{@Go@_@eBDcAY[Gc@PeABw@Eq@Sw@x@QbBaB`BcBbA_AhAuB|@sC|@uC~@kE`AkEkBt@qCf@oCh@qCf@eCl@gCj@mB?oB?gD{@o@_@[e@y@{AE]Q_@a@_@EKBUJO?On@?Bc@GSAQQg@FcAGm@MaADqABg@AUYM_@a@mA_A}@mAu@g@WY{B}Be@]{@cAw@_@aAy@mB{Bw@o@q@c@eB_AoIcEgFkD_Ay@^gDd@eE_BwD_AyAk@i@{AA@x@GrAP~AF`BOdAk@Rg@?Sa@?wBCqC?wA",
      options: { checkpoints: {} },
      enabled: true,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      id: "3ab1e6c7-2a76-4f89-bca4-ecc0f195dbd8",
      distance: "67.30",
      polyline:
        "cnaiHjgcrV@oCPQD]J]l@a@VYRyABcB@gFC{FC{FAmCAmC}C@}C@_D@yB?yB@yB?qDFs@Mu@a@aBg@kAD{CpAeDCeDA_DCaDC_DAaDC_DC_DAaDCk@aFs@{C]cA_AgCgB_Ec@q@aBmBk@Ws@C_CN_CN_CPu@ViDfAq@Bw@Es@U_Am@}BcB}Ak@{Ak@cBmBiA}CIq@KcAe@qAo@s@}AuA_BwAcAoAyBaDeA_AcAi@qBMk@]s@sAq@kBQS{AwAkAq@}B[_CY}BM_CK}BMyAF_BH_BHcDCaDCy@Q{Ao@gAs@_B{AuAeAWiAsAgCcAiCWo@sAuBqAwBqBiCqBiCqBiCi@aAoAsF[}BSmDMqFGeAGaAg@kEg@kEs@sCsBaEk@yAk@aCk@aCo@mBeAiAeB[eBQeBSMSOc@?kApAgEx@iDn@gC~@cD~@aDb@}@hBeBjBeBpBsBpBsB`@k@d@mA`@sD`@qD^qDAaECaEA_EBqAPgBbAqFbAsF|@_Ez@_E|@_ELw@D}@BsAOwEMwEMwEIiCIgCBaBHqAP}@dAaEdAaEbAaEZ{@`AmAjBs@lBs@zB_AzB}@`Ag@nCaAz@[lCg@nDe@nDg@nDg@hBa@fB_@|Bi@`@ST_@?cGAcG?w@rDApDArDCtCAtCAnCAnCAnCApCKhAaAlAgCh@{Br@qCvByDd@g@rAcAt@a@fDq@hDs@lAJlBb@jB`@xBf@v@ZbAbA~@nCz@`Dx@jBv@dA~@f@~@LvAEz@K|AQtBKfANXL??Nc@Jw@@GEoAk@Gq@c@g@E[WM?a@AFi@BMl@Qx@@f@a@FG\\CV_BIm@Ga@OMg@Ja@s@SoBVCNKRO_@y@Aq@~@Cv@d@`@B^e@DETJd@b@JTXf@|@F~ACLa@b@Q`@WFF|@|@`@A\\CJA@LIJ?JJZLBBDIJ?TER?n@DBNHLd@`@JBUDq@IkCGiCDs@V_A\\w@x@}@vAuB\\y@Ps@N{A?y@Ss@_@USYF?ZDRON@d@fABXEXDJRBXc@L?HRN\\VWD[JEJv@J?VkAL?FbAKf@OTWRIb@Yv@S@SJGFq@|@aAj@u@j@U\\Y^wArAETRHVK`@CFDHDF^ANGHIp@AD]CQJUZGPKHCJAJCbAELKLGb@IfAERQPYPc@Py@F_A@{@VwBn@gBfAQZUb@WZy@|@WVOLM~@DB^Vr@h@??B@Ld@??FVFF??l@h@zArAnCfAdCRfCPfCRhAR~AZpAbApA`ArAlApAlArBMxA{A`CeCbByB`BwBbBwBFAvBm@vBm@p@Nv@\\vBxBz@|@hCpA`CXvA~@fAzAfAzAd@p@`BlC`DdBpC?vCuAFChA{Bp@oDhAgDfBaCdBcCZw@b@gAbAmBdAo@vC@tC@_@yCc@uDe@uDe@sD_@cE@uBbA_FfBqEhAqEf@aBVk@|@uB|@sBj@{Ch@}CR_DP_D`AcFbAeFXcAfAmDfAoDfAoDt@sEr@uEt@uE|@uD~@wD^mAvAwEvAwEhAqDjAoDnAcDnA{ETa@d@OfB?zAAdDH@xC?jBAt@?fD?dDGhCd@jDHfCD|AQxCSxCPnBvAvBxAvBf@h@LHt@V\\Dl@?`C[l@HZLn@b@z@tAhBvETf@b@t@vAmCrA_CZu@Ry@Js@H{AEqAUmE??[qFIu@Oo@w@qBMo@Kq@Co@?iBJmAXcBdAuDbAsDJaCeAqB`BuB`BuBt@c@B???\\AlB\\nB\\tBb@vB`@NH??NHb@h@zBnDzBnDRj@Lp@Dj@@`A???fD`@tCjDCfBDr@N??`AVFBH_AJc@HMPIH@l@NjA^VBj@Gf@Sn@Wn@Uz@?p@`@r@Xh@t@Hf@Oz@Q~@Gn@Xl@TVb@z@j@jAh@lAZn@X\\TNTJR@PCLMLa@JQL[NQd@{@l@gAb@{@x@qBr@eBf@qAf@qAb@q@d@STMXk@j@Mv@Cr@Ar@@r@Dl@?^Bl@Bz@@t@`@R\\f@t@v@a@nB}@^Nf@h@DDFC\\DT?t@OTGVS^g@HW@SVmEJe@JiABe@Hc@Xk@`@k@\\STARBRHVTRXBJBJ@RCZu@pCG`@?RHZFLLHl@APERIn@B`@Dp@L`@^V\\Z`@VLb@D?\\CXMl@AF_@@S`A[tAm@|BE@Ia@e@Pa@Pi@@QCUCS@OPGXItAUpBKb@Q@MNUXWd@CJCLO~AAAK\\WPMNMGGEOJEd@@Pe@hAAEl@jAh@f@rA`BHXVl@Zt@\\hAr@V\\^A?_AI]hACBg@^c@v@AhBCbBP`BBdAC^SzBUdAq@t@}@\\Oh@Yp@Qr@AD?pAO`B?J@n@Ct@MjAIVQr@Tp@]vAEBUPQhAUHKh@Al@A@??UV??A@ME]?GKEkB???Go@ZQZ_@~@[v@Mb@G`@K`@?nG?lARzBCx@Ej@m@~BI~@B~@NbA`AdCB^QLe@@uA?eA{@g@iAUoAMgDMwAa@yCa@yCK_@q@qCs@qCoBqEgC{C_@_@]a@s@{Ai@wBYsA]g@YYYIu@?DpCDn@VvDTpBNhBH~AB`DCnGCrECpECrEEjBOfDOzAe@hDk@nC_@lBc@t@GBKJCL?TSjA}A|CUTa@p@c@`@i@v@Ex@v@~AdBrDbA~Bv@tBv@rBbAjDfAhEdA|DVdAz@zDx@lCx@lCj@tAtAzBnAnAnAnAdAl@`Ah@bD~AdDx@dDx@fA`@LFjCjBp@p@dCpDvAlCvAjCJPpAnATZZr@bAfD`AfDt@bBj@l@|@r@`BdA|@`Ar@hA|@~Ah@|Bh@bD\\n@b@dAvAlDvAlDjA|DRh@\\t@`@\\fAN`BBb@`@BPFJJF\\z@@bA@tC@vC?nDcB|AcB|Ag@d@mAfBmAdBcBtA}AdBaApBc@z@u@fEuAdBkBb@sApAaBdBaAhA[j@oB|CoB|CoB|CKRi@~@MJaBBgADeD?eD@gD?iB?iB?mCBmCBmCBqCFoCFw@G_As@M\\Y\\_B@_B?_D@_DB_D@_DB_D@_DB_D@_DBkCBkC@kC@kCBwC@ATgAVw@@c@DSk@KO]Ss@[}@m@w@a@sAY}@Gg@Im@Kw@_@IE[[kAyA_@o@_@u@Oc@y@aAM[EKBi@DCHOB]EUBWAGKQAOB}@Fw@@QF]?YHiAASGyABs@GUMWEQEu@BWQiAU]a@CC?G?]XSDGDSBKFSXe@b@Qd@_@t@KHMXEByAKm@Dc@HKF}@G_@Ua@OU]Kg@Do@CmBCsFFs@No@Rk@tBmCXi@L]VwA^qCuBUyAc@wAe@k@g@g@y@YYe@]i@MeA?cAFuCl@aBn@Hd@LfDFxADvEYtCYtC_@dCKz@[nAa@z@a@l@yA|COh@kArE{@tFMhCBjF@lF@jF@lFoBi@]]a@a@g@Q_@Bm@TcBXeBX}AAsB?qBAeA^i@^gCtC]`@yA~@aClCUj@]h@o@r@{A`A}A`Ai@j@gClDkB`BkB`BkBbBSXUZiAnCq@~@g@d@{CxAYVKXMhBO^sArAaBxBaBxBeCpBOTIz@AbEArF?rF@rF@nFBnF@pF@pFBrF@pFBpF@pEFjA~CA~CA~CA~CAjCAjCAhCAjCChDAfDAhDChC?jCAhC?jCAnC?lCA^l@A|A?xB@vB@~CB~C@`CJt@HHf@@?tAGd@KdACl@Kh@Of@M`@H?FbFDlARn@`AjBRnA?jC?jCL?hD?fD@hD?tC?vC@tC?vC?hC?hC@fC?dAzFl@fDr@nFLdF@pE@nE@pE?pF?rF?pF?pF?xE?bG@`G?bG?bGFtDBdA^~Ex@tEv@zBv@zB|AlC`BvB`BvBpBdCpBdCpBdCpBdClCbDjCdDlCdDjCdD|JjMP^h@v@v@bAx@bALP~@jAp@x@n@x@t@z@XZdDtD^RX\\hArA@V@NBFZs@DEFJLRJJNVV`@f@n@^b@Vn@?NEHy@kA_BuBuBiC}BsC}BsC_BoB?wA?eG?eG@gG?eGFuDAw@CeDAgDAkF?mF?kFAmF?uFAwF?uFAwF@mD@mD@_GEqA@u@Ns@HUj@q@ZCnDCnDCzCA|CAzCChCAhCAfCAlBCjBCbDIbDIbDIx@Kl@DFPLHPCJOfAo@jAi@lBw@lBw@DdE@fAR[RQrAkBrAiBvAeBpBmBpAs@f@[r@g@NKv@hAtC`Cz@d@FBJYLOj@HNG^{@LL|@v@TJXFh@Gl@XZBJCvAkAt@eAnAiBZ]Tw@VSDQFIb@[N[VY\\e@l@iAp@{A\\k@|@bBlAjDNb@Jb@PjABlDUhFUjFObCW|DKhCD|C`@fDfA~DrArDh@fCH\\j@fFj@dFl@dFj@fFf@bFT~At@hFr@hFf@jEH~@@`AOnEQpEGZ[zA{@hD}@hDOz@GpAB~BZvCb@`Bn@jAl@jAlBfDt@pAt@tB`AjD`AvD`AxDjA`FhAbFx@lEdAnFbAnFbApFbAnF?lFAvF?vF?vFEnDCnDZfBdA`DZ`AZtAf@hEd@hEd@nFd@pFf@pF`@vEPz@x@jBNf@Ft@W~DJhAL`@dAlAXh@Ld@@lCl@xD?z@\\v@TXNj@J`AFrADhE[rBA`@F`Ax@nC`AtB`AtBtBpALXJpA?P?xADb@\\~@Hl@NlEv@hEb@fBL~ExBN`@Pd@HLLN^L|@JZPV\\Pd@Nb@Xt@r@b@r@Tr@l@`EDn@FZh@p@jBpAT`@Lb@BtBBjEd@~AZj@Zx@ZrATtAZrDN~@Rj@T^XZz@`@j@h@Nd@DvA?jAUtEDdAR`Aj@vALfAAbAMxA?lAFnAb@tD`@tD\\rCh@zFLtCDbDDdDBdF@fFDd@Ld@`B`EDLjAhFT|ATxCFrBA|@Or@a@|@a@xAe@xD_@|Fo@zA[`@s@d@g@n@[l@a@dB[pBWtDWvDK|@m@zByAhDyAhDe@tFe@rF?TDfBN~A\\zE?xBItBBxBT~ET~EHd@Dp@Ap@e@dCShCk@vDAdCUxASf@m@f@gBVgBV[AUM}AqAc@UuAUYJ_CdBeBlBw@lAu@tAmAtCq@~Bo@xBUReDv@eDv@q@DWHo@`AeAxCc@x@Ij@E|@BnA\\bD\\bDPx@B~B@nBR~CP|C@h@SxD@pBV|CT|CV`F?j@B|DB|D@zD~AI~AK~B?|@LrBRrBPh@LNBl@Z`ArAPj@Hj@BpCAjGAhG?jGAvAGzFIzFIp@Qb@aAvAcAt@mBv@_CXaDD_A@mAJcCn@uBbAsBbAuBbAw@Z{Al@}Aj@{C|@k@Be@I_@[Yc@W}@KaABeEGsFCi@Ig@O[a@m@c@a@yAgAuCi@m@Hw@ToAhA[b@Yb@wB~Di@vAuAhE}@dBoCzCoCzC_@f@S`@[l@aAfCmAdE[x@a@b@cAm@}BwB{AsBsAkBsAiBi@m@uA[aDwA_@_@Wk@YgAmAyEsAsCuAuC]_@c@OkBY_@Wc@k@aAeBaAeBi@g@Uv@cBtCaBvC@{C?{@NkFNkFLmFNkFNkFLkFNkFN_GN}F?}F?}FA_G?}F?}FA}FUgGWgGWeGWgGKeFMeFDyFVuEVsEp@oFp@oFn@mFp@oFn@oFp@mFEqEEqEEqEA}Ap@qFn@oF^yD^wD^yDi@_FwAwDyA}B{A{Bm@oB]wD]wD_@wDMwAm@aBuB{BwB}BwB{B{@{B{@}B{@yDi@{Eg@{Ei@}Ei@{EOkA?Eg@oDg@mDg@oDFCU}AS{AIk@SaBa@kDU}AGa@YaCUyA]_CG_@c@uCYiBG[WgBY}Bi@kDK_@e@oBi@aCWeAa@oBIg@M}@Ag@B}ELm@MYAa@BYFk@Je@Pm@`@{@f@iAh@qALw@?{@I}@AcAJsAb@yB^aBf@{Cv@eERuAAmAGi@{AvAiAVc@AWEKCOCGAc@GWCa@EMA??y@gEaAwESgBIoC@eC`@gk@Z{c@BkF@c@DmGJgSBwCFiE@}ABaANeH@oDBqG?UFoFBeE@uA?yA?_AAw@EoAC[IaBk@uEW_B_@yAQk@c@cAO[ISgAoBWiA]m@i@s@k@{@k@{@m@rAIq@j@l@DIpB~Bn@z@Vr@|@lBXn@`@bA@@Pf@\\vAXxAl@tELdBDp@Jn@@v@?xCAtACdEGnF?TAnDA`BAnDSfJA|AGhEAlAAhAI~OAfBElGErF?ZMlQO|TQ`UOzU?FHfCRfB`AvEx@fE??a@Qa@OiAe@cA_@CA]Oc@OeBq@cAa@a@Qa@OeAa@a@Oa@OAAa@GKCy@IWC_ADS?c@Bc@@c@@oCHgAD_@@C?c@@W@K?aAEE?[IKCo@OIA{A?kB@eB?i@AgAEi@CaACKA_BCaAAc@XA@O^E|@?F@t@JhE?XDhEAtG?xAA`A?FAlCATGt@g@pHIbAEd@AN?@AL?n@?h@?@BdEJtC?J@n@InAG`@CVOd@KZKVMPi@l@sBvAuBxAeAz@cAfA{@pB_@pBMzCDrDU?_CBkB@_ATk@h@cArBqBlCoBlCsA~A_Ah@g@R_DT_AR_@N_BxAmBzAkBxAiAh@u@ZaDr@aDr@qAR{BD{BFmABqAS_Ci@u@u@aAw@a@w@{@kEq@cAQMk@c@k@Eq@Tm@t@q@f@aA^}@Nq@KaAo@s@s@sAu@mAScCeAgAQuBGuBGc@CiC[qAc@}@m@yByBsAeCkAkBo@o@}@a@kCQiBa@iA[uAu@mCqAuAo@yCgByCgBa@o@_@aAQcAOwA?YN}@`@aBXq@r@qAdA_Bp@gBRmAXmCNgCDuC`@mD`@mDT_BXmA`AmCl@sBLqAIeCQ}CDgDBiDOmBUoAcAiD[iBk@sEYgDy@aEaAmCc@w@q@}@gCmDeAOgBNaDf@sBJwCa@iBcAiCcBmAiBwAiB_Bo@_Bo@q@c@cAiA[e@y@q@kASICm@s@Mu@OwB{@}DGq@FaB[qBiBaCQiCSkCJkCJkCp@_EhBPfBNxAVdBP`BPnA\\~@Fd@SVUjBuD|@sATQ`@CpADn@Gf@Wd@_@h@o@rAgChBkC^]hBi@nAi@t@g@`@WvBs@\\GdB@fBBRErAg@z@WTCT@ZFvAl@HF\\?ZGlBeAREd@?ZHtAv@j@\\|@VnBPpDL\\C\\M|BkA~BkA|BkA|CgBfC{CvA}AxA_B`@g@`AkB`AkBNe@h@mCHu@?gAH}B@wAEmDGs@u@yEw@wEk@oCSiASmB_@uACi@?a@HgBC]SmAe@aBa@}@[sA[yBKe@w@aAk@e@u@{@WQwAq@uA{@SYaAm@y@GQIU]sAo@u@m@YM_@EkA]gAm@s@Ku@UMIKUYi@k@y@[Oe@_@{@a@y@QwBw@_@]cA]i@WuByAgBaBWK}@S[Uq@{@IWAUDc@^c@l@_@T[Pk@BSCwAMi@}@cBi@Yg@M[A[N_@Xe@B_@?_AKWGS?mAJy@EeA?yBTeA@{@Hi@A[B_ASgBi@e@UYG_@Bq@Iw@m@ICM@c@T_@NK?[Bn@aBf@aAPu@Jy@Pw@l@uAz@y@r@y@dAcBzA_B~AkAn@w@bB{Bj@_@`@OpB_@h@c@d@Ob@CzA?zA?~CHbANh@RRAJM@[IY[]]k@}@}Au@_AoAm@s@g@oAm@w@s@a@i@Qe@Eg@@m@Pc@JGVMr@KtB@jB]dAChDd@x@PpCD|ARlCTzA\\FBZMLRVL\\v@d@ThA|@jAj@lAz@h@J~A\\~A^dB`A@CZ[PKv@UhAk@`AUdBa@f@GzCUT?X@hC]v@?r@JdAf@XFZBTIVQXMvCQ`ASf@Kx@GnAQxB@j@D`@BbAOPK`@i@LWZcBD{@Go@Mg@Q}@DcAY[Gc@PeABw@AUC[Sw@x@Q`B_B~AaBfAcAhAuB|@sC|@uC~@kE`AkEkBt@uCh@wCh@uCj@}Bh@_Ch@qB?oB?cD{@o@_@[e@y@{AAGCUQ_@a@_@EKBUJO?On@@@_@@EGSAQQg@FcAGm@MaAHyBAYYI_@a@mA_A}@mAu@i@sCuCe@]{@cAMEm@[}@w@mB{Bo@i@mAw@qAo@uEmByCoBkEgCsAcBh@eBb@gD_@gDcAuCkAw@cBGGv@A`BNnABzB_@p@s@HYKAmACqBCgB@iA",
      options: {
        checkpoints: {
          hidden: [
            "03560c69-9f31-4253-ba69-4e949c652338",
            "0429019d-6634-4e02-8281-1a406a5e4106",
            "0599774b-1f09-4627-ab4b-f6256633a45d",
          ],
        },
      },
      enabled: true,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
    {
      id: "5ab9c9c3-6210-47cd-aab9-d1279e04dd34",
      distance: "32.40",
      polyline:
        "cnaiHjgcrV@oCPQD]J]l@a@VYRyABcB@gFC{FC{FAmCAmC}C@}C@_D@yB?yB@yB?qDFs@Mu@a@aBg@kAD{CpAeDCeDA_DCaDC_DAaDC_DC_DAaDCk@aFs@{C]cA_AgCgB_Ec@q@aBmBk@Ws@C_CN_CN_CPu@ViDfAq@Bw@Es@U_Am@}BcB}Ak@{Ak@cBmBiA}CIq@KcAe@qAo@s@}AuA_BwAcAoAyBaDeA_AcAi@qBMk@]s@sAq@kBQS{AwAkAq@}B[_CY}BM_CK}BMyAF_BH_BHcDCaDCy@Q{Ao@gAs@_B{AuAeAWiAsAgCcAiCWo@sAuBqAwBqBiCqBiCqBiCi@aAoAsF[}BSmDMqFGeAGaAg@kEg@kEs@sCsBaEk@yAk@aCk@aCo@mBeAiAeB[eBQeBSMSOc@?kApAgEx@iDn@gC~@cD~@aDb@}@hBeBjBeBpBsBpBsB`@k@d@mA`@sD`@qD^qDAaECaEA_EBqAPgBbAqFbAsF|@_Ez@_E|@_ELw@D}@BsAOwEMwEMwEIiCIgCBaBHqAP}@dAaEdAaEbAaEZ{@`AmAjBs@lBs@zB_AzB}@`Ag@nCaAz@[lCg@nDe@nDg@nDg@hBa@fB_@|Bi@`@ST_@?cGAcG?w@rDApDArDCtCAtCAnCAnCAnCApCKhAaAlAgCh@{Br@qCvByDd@g@rAcAt@a@fDq@hDs@lAJlBb@jB`@xBf@v@ZbAbA~@nCz@`Dx@jBv@dA~@f@~@LvAEz@K|AQtBKfANXL??Nc@Jw@@GEoAk@Gq@c@g@E[WM?a@AFi@BMl@Qx@@f@a@FG\\CV_BIm@Ga@OMg@Ja@s@SoBVCNKRO_@y@Aq@~@Cv@d@`@B^e@DETJd@b@JTXf@|@F~ACLa@b@Q`@WFF|@|@`@A\\CJA@LIJ?JJZLBBDIJ?TER?n@DBNHLd@`@JBUDq@IkCGiCDs@V_A\\w@x@}@vAuB\\y@Ps@N{A?y@Ss@_@USYF?ZDRON@d@fABXEXDJRBXc@L?HRN\\VWD[JEJv@J?VkAL?FbAKf@OTWRIb@Yv@S@SJGFq@|@aAj@u@j@U\\Y^wArAETRHVK`@CFDHDF^ANGHIp@AD]CQJUZGPKHCJAJCbAELKLGb@IfAERQPYPc@Py@F_A@{@VwBn@gBfAQZUb@WZy@|@WVOLM~@DB^Vr@h@??B@Ld@??FVFF??l@h@zArAnCfAdCRfCPfCRhAR~AZpAbApA`ArAlApAlArBMxA{A`CeCbByB`BwBbBwBFAvBm@vBm@p@Nv@\\vBxBz@|@hCpA`CXvA~@fAzAfAzAd@p@`BlC`DdBpC?vCuAFChA{Bp@oDhAgDfBaCdBcCZw@b@gAbAmBdAo@vC@tC@_@yCc@uDe@uDe@sD_@cE@uBbA_FfBqEhAqEf@aBVk@|@uB|@sBj@{Ch@}CR_DP_D`AcFbAeFXcAfAmDfAoDfAoDt@sEr@uEt@uE|@uD~@wD^mAvAwEvAwEhAqDjAoDnAcDnA{ETa@d@OfB?zAAdDH@xC?jBAt@?fD?dDGhCd@jDHfCD|AQxCSxCPnBvAvBxAvBf@h@LHt@V\\Dl@?`C[l@HZLn@b@z@tAhBvETf@b@t@vAmCrA_CZu@Ry@Js@H{AEqAUmE??[qFIu@Oo@w@qBMo@Kq@Co@?iBJmAXcBdAuDbAsDJaCeAqB`BuB`BuBXQ??ZQ`@ApCh@pCf@pCh@??TD^Rb@h@zBnDzBnDRj@Lp@Dj@@fD???`A`@tCjDCfBDr@N??`AVFBH_AJc@HMPIH@l@NjA^VBj@Gf@Sn@Wn@Uz@?p@`@r@Xh@t@Hf@Oz@Q~@Gn@Xl@TVb@z@j@jAh@lAZn@X\\TNTJR@PCLMLa@JQL[NQd@{@l@gAb@{@x@qBr@eBf@qAf@qAb@q@d@STMXk@j@Mv@Cr@Ar@@r@Dl@?^Bl@Bz@@t@`@R\\f@t@v@a@nB}@^Nf@h@DDFC\\DT?t@OTGVS^g@HW@SVmEJe@JiABe@Hc@Xk@`@k@\\STARBRHVTRXBJBJ@RCZu@pCG`@?RHZFLLHl@APERIn@B`@Dp@L`@^V\\Z`@VLb@D?\\CXMl@AF_@@S`A[tAm@|BE@Ia@e@Pa@Pi@@QCUCS@OPGXItAUpBKb@Q@MNUXWd@CJCLO~AAAK\\WPMNMGGEOJEd@@Pe@hAAEl@jAh@f@rA`BHXVl@Zt@\\hAr@V\\^A?_AI]hACBg@^c@v@AhBCbBP`BBdAC^SzBUdAq@t@}@\\Oh@Yp@Qr@AD?pAO`B?J@n@Ct@MjAIVQr@Tp@]vAEBUPQhAUHKh@Al@A@??UV??A@ME]?GKEkB???Go@ZQZ_@~@[v@Mb@G`@K`@?nG?lARzBCx@Ej@m@~BI~@B~@NbA`AdCB^QLe@@uA?eA{@g@iAUoAMgDMwAa@yCa@yCK_@q@qCs@qCoBqEgC{C_@_@]a@s@{Ai@wBYsA]g@YYYIu@?DpCDn@VvDTpBNhBH~AB`DCnGCrECpECrEEjBOfDOzAe@hDk@nC_@lBc@t@GBKJCL?TSjA}A|CUTa@p@c@`@i@v@Ex@v@~AdBrDbA~Bv@tBv@rBbAjDfAhEdA|DVdAz@zDx@lCx@lCj@tAtAzBnAnAnAnAdAl@`Ah@bD~AdDx@dDx@fA`@LFjCjBp@p@dCpDvAlCvAjCJPpAnATZZr@bAfD`AfDt@bBj@l@|@r@`BdA|@`Ar@hA|@~Ah@|Bh@bD\\n@b@dAvAlDvAlDjA|DRh@\\t@`@\\fAN`BBb@`@BPFJJF\\z@@bA@tC@vC?nDcB|AcB|Ag@d@mAfBmAdBcBtA}AdBaApBc@z@u@fEuAdBkBb@sApAaBdBaAhA[j@oB|CoB|CoB|CKRi@~@MJaBBgADeD?eD@gD?iB?iB?mCBmCBmCBqCFoCFw@G_As@M\\Y\\_B@_B?_D@_DB_D@_DB_D@_DB_D@_DBkCBkC@kC@kCBwC@ATgAVw@@c@DSk@KO]Ss@[}@m@w@a@sAY}@Gg@Im@Kw@_@IE[[kAyA_@o@_@u@Oc@y@aAM[EKBi@DCHOB]EUBWAGKQAOB}@Fw@@QF]?YHiAASGyABs@GUMWEQEu@BWQiAU]a@CC?G?]XSDGDSBKFSXe@b@Qd@_@t@KHMXEByAKm@Dc@HKF}@G_@Ua@OU]Kg@Do@CmBCsFFs@No@Rk@tBmCXi@L]VwA^qCuBUyAc@wAe@k@g@g@y@YYe@]i@MeA?cAFuCl@aBn@Hd@LfDFxADvEYtCYtC_@dCKz@[nAa@z@a@l@yA|COh@kArE{@tFMhCBjF@lF@jF@lFoBi@]]a@a@g@Q_@Bm@TcBXeBX}AAsB?qBAeA^i@^gCtC]`@yA~@aClCUj@]h@o@r@{A`A}A`Ai@j@gClDkB`BkB`BkBbBSXUZiAnCq@~@g@d@{CxAYVKXMhBO^sArAaBxBaBxBeCpBOTIz@AbEArF?rF@rF@nFBnF@pF@pFBrF@pFBpF@pEFjA~CA~CA~CA~CAjCAjCAhCAjCChDAfDAhDChC?jCAhC?jCAnC?lCA^l@A|A?xB@vB@~CB~C@`CJt@HHf@@?tAGd@KdACl@Kh@Of@M`@H?FbFDlARn@`AjBRnA?jC?jCL?hD?fD@hD?tC?vC@tC?vC?hC?hC@fC?dAzFl@fDr@nFLdF@pE@nE@pE?pF?rF?pF?pF_B{@_B{@oC_AmC_AcDiAcDiAcDiA{AWyAWeDVkBt@qCf@oCh@qCf@wBf@yBf@[HqB?oB?cD{@o@_@[e@c@y@Ua@E]Q_@a@_@EKBUJO?Or@??c@GSAQQg@FcAGm@MaAHyBAQYQ_@a@mA_A}@mAg@]w@s@iBmBe@]a@e@Y]{@a@}@w@kByBy@q@eAq@qAo@@CsCwAkBw@qCyAoC{AeA{AEwALmBX_BFeA]{Ae@aBg@uAo@Ec@e@wA?IX?t@?lANpAFfBGx@i@Je@H_@QAoB@kCCwB",
      options: {
        checkpoints: {
          hidden: [
            "02e6b0c9-d243-4b67-905d-e7925051d2c4",
            "03560c69-9f31-4253-ba69-4e949c652338",
            "0429019d-6634-4e02-8281-1a406a5e4106",
            "0599774b-1f09-4627-ab4b-f6256633a45d",
            "0699774b-1f09-4627-ab4b-f6256633a45d",
            "0799774b-1f09-4627-ab4b-f6256633a45d",
          ],
        },
      },
      enabled: true,
      Event: { id: "3fcae798-3dfd-4a78-afed-a28bea41f686" },
    },
  ],
};
