'use client';

import { ThemeUIProvider } from 'theme-ui';
import theme from '../src/utils/theme';

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// };

import '@aws-amplify/ui-react/styles.css';
import '../styles/globals.css';
import 'mapbox-gl/dist/mapbox-gl.css'


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
				<ThemeUIProvider theme={theme}>
        <main>{children}</main>
				</ThemeUIProvider>
      </body>
    </html>
  );
}
