// src/utils/theme.ts
import { Theme } from "theme-ui";

const palette = {
  white: "#ffffff",
  black: "#000000",
  grayLight: "#f0f0f0",
  grayMedium: "#cccccc",
  grayDark: "#555555",
  grayDarker: "#3f3f3f",
  grayDarkest: "#1a1a1a",
  red: "#de4747",
  blue: "#3096f0",
  yellow: "#ffd700",
};

export default {
  useColorSchemeMediaQuery: true, // Enables system preference detection
  colors: {
    primary: palette.black,
    iconColor: palette.grayDark,
    secondary: palette.grayDarker,
    background: palette.white,
    text: palette.black,
    muted: palette.grayLight,
    highlight: palette.yellow,
    accent: palette.blue,
    gray: palette.grayDark,
    skeletonLight: palette.grayLight,
    skeletonDark: palette.grayMedium,
    menuBorder: palette.grayMedium,
    inputBackgroundColor: palette.grayLight,
    inputFocusBorderColor: palette.grayDark,
    secondaryButtonBackground: palette.grayLight,
    secondaryButtonBackgroundHover: palette.grayMedium,
    primaryButtonBackgroundHover: palette.grayDark,
    buttonHoverBackground: palette.grayDark,
    dropdownMenuBackground: palette.grayLight,
    dropdownMenuHoverBackground: palette.grayMedium,
    activityOverviewBackgroundColor: palette.grayLight,
    selectedBackground: palette.grayDark,
    selectedBackgroundText: palette.white,
    editorBackground: palette.grayLight,
    iconButtonBackground: palette.grayLight,
    tooltipBackground: palette.grayMedium,
    iconButtonDisabled: palette.grayMedium,
    iconButtonBackgroundDisabled: palette.grayMedium,
    buttonBorderColor: palette.grayMedium,
    divider: palette.grayMedium,
    dividerDark: palette.grayDark,
    sideMenuBackground: palette.white,
    sideMenuDivider: palette.grayMedium,
    sideMenuRightBorder: palette.grayMedium,
    menuItemBackgroundHoverColor: palette.grayLight,
    buttonBackgroundHoverColor: palette.grayMedium,
    sideMenuHoverBackground: palette.grayLight,
    skeletonGradient1: palette.grayMedium,
    postCardTextBackground: palette.white,
    cancelButtonColor: palette.grayMedium,
    postCardBorder: palette.grayMedium,
    postCardBorderDark: palette.grayDark,
    inputFocusBackground: palette.grayLight,
    inputBorderColor: palette.grayMedium,
    defaultAvatarBackground: palette.grayMedium,
    alertBackground: palette.grayDark,
    alertForeground: palette.white,
    menuBoxShadow: `${palette.black}0d`,
    postCardDefaultImage: palette.grayLight,
    blackBoxColor: palette.black,
    chartTooltipBackground: palette.grayMedium,
    chartAxes: palette.black,
    spinnerButton: palette.white,
    videoAccent: palette.blue,
    messagesBackGround: palette.grayLight,
    messagesBorderLeft: palette.grayMedium,
    modalBackground: palette.black,
    modalClose: palette.white,
    floatingMenuBackground: palette.grayDarker,
    floatingMenuIcon: palette.grayLight,
    footerMenuLink: palette.grayDark,
    footerBackground: palette.grayLight,
    blogHeaderBackground: palette.grayLight,
    textMuted: palette.grayDark,
    publicMenuBackground: palette.white,
    publicBackground: palette.white,
    modes: {
      dark: {
        footerBackground: palette.grayDarkest,
        menuBorder: palette.grayDark,
        iconColor: palette.grayLight,
        primary: palette.grayLight,
        secondary: palette.blue,
        background: palette.grayDarker,
        text: palette.white,
        muted: palette.grayDark,
        highlight: palette.yellow,
        accent: palette.blue,
        gray: palette.grayDark,
        skeletonLight: palette.grayDarker,
        skeletonDark: palette.black,
        inputFocusBorderColor: palette.white,
        inputBackgroundColor: palette.grayDark,
        postCardBorderDark: palette.grayDark,
        secondaryButtonBackground: palette.grayDark,
        secondaryButtonBackgroundHover: palette.grayMedium,
        primaryButtonBackgroundHover: palette.grayLight,
        sideMenuRightBorder: palette.grayMedium,
        activityOverviewBackgroundColor: palette.grayDark,
        sideMenuBackground: palette.black,
        blackBoxColor: palette.grayLight,
        textMuted: palette.grayDark,
        tooltipBackground: palette.grayDark,
        editorBackground: palette.grayDark,
        postCardTextBackground: palette.grayDark,
        iconButtonBackgroundDisabled: palette.grayDark,
        iconButtonBackground: palette.grayDark,
        inputFocusBackground: palette.grayMedium,
        buttonBackgroundHoverColor: palette.grayDark,
        sideMenuHoverBackground: palette.grayDark,
        skeletonGradient1: palette.grayDark,
        postCardBorder: palette.grayDark,
        menuItemBackgroundHoverColor: palette.grayMedium,
        buttonBorderColor: palette.grayDark,
        cancelButtonColor: palette.grayDark,
        defaultAvatarBackground: palette.grayMedium,
        divider: palette.grayDark,
        alertBackground: palette.grayMedium,
        alertForeground: palette.black,
        menuBoxShadow: `${palette.black}b0`,
        postCardDefaultImage: palette.grayMedium,
        chartTooltipBackground: palette.grayMedium,
        chartAxes: palette.white,
        dropdownMenuBackground: palette.grayDark,
        dropdownMenuHoverBackground: palette.grayDarker,
        floatingMenuBackground: palette.black,
        floatingMenuIcon: "red",
        footerMenuLink: palette.grayLight,
        blogHeaderBackground: palette.grayDarkest,
        publicMenuBackground: palette.grayDarkest,
        publicBackground: palette.grayDarkest,
      },
    },
  },
  messages: {
    default: {
      backgroundColor: "messagesBackGround",
      borderLeftColor: "messagesBorderLeft",
    },
  },
  text: {
    aboutHeader: {
      fontWeight: 400,
      fontSize: "40px",
      lineHeight: "48px",
      letterSpacing: "-1px",
      marginBottom: "16px",
    },
    aboutHeaderSmall: {
      fontWeight: 400,
      fontSize: "32px",
      lineHeight: "40px",
      letterSpacing: "-1px",
      marginBottom: "8px",
    },
    aboutParagraph: {
      marginBottom: "28px",
      paddingTop: "16px",
      fontSize: "16px",
      lineHeight: "28px",
      fontWeight: 300,
    },
    menuItem: {
      "&:hover": {
        backgroundColor: "menuItemBackgroundHoverColor",
        borderRadius: "5px",
      },
      cursor: "pointer",
      color: "text",
      padding: "5px",
      width: "100%",
      fontSize: ["17px", "15px", "15px"],
      textDecoration: "none",
    },
    error: {
      color: palette.red,
      lineHeight: "24px",
      fontSize: "15px",
    },
  },
  boxes: {
    skeletonButton: {
      height: "32px",
      width: "32px",
      borderRadius: "5px",
    },
    menuItem: {
      padding: "10px",
      background: "background",
      borderColor: "menuBorder",
      borderWidth: "1px",
      borderStyle: "solid",
      borderRadius: "5px",
      zIndex: "4",
      boxShadow: "0 3px 8px rgba(0, 0, 0, 0.3)",
      animation: "fadeIn .2s;",
    },
    // figure: {
    //   backgroundColor: "red",
    // },
    sidebarMenuItem: {
      fontSize: "15px",
      paddingLeft: "15px",
      paddingY: "10px",
      borderRadius: "5px",
      width: "100%",
      "&:hover": {
        background: "sideMenuHoverBackground",
        ".childButton": {
          transform: "scale(1.1)",
          transition: "background 0.5s, transform 0.5s ease-out, fill 0.5s",
        },
      },
    },
    componentCard: {
      maxWidth: "690px",
      // backgroundColor: [
      //   "background",
      //   "activityOverviewBackgroundColor",
      //   "activityOverviewBackgroundColor",
      // ],
      borderColor: [
        "background",
        "activityOverviewBackgroundColor",
        "activityOverviewBackgroundColor",
      ],
      borderRadius: ["0px", "5px", "5px"],
      // padding: ["10px", "20px", "20px"],
      position: "relative",
      marginY: ["0px", "20px", "20px"],
    },
    dropdownMenuItem: {
      padding: "10px",
      cursor: "pointer",
      "&:hover": {
        backgroundColor: "dropdownMenuHoverBackground",
        borderRadius: "5px",
      },
    },
  },
  links: {
    mainMenuItem: {
      fontWeight: 600,
      padding: "5px",
      color: "text",
      "&:hover": {
        backgroundColor: "menuItemBackgroundHoverColor",
        borderRadius: "5px",
        color: "text",
      },
    },
    profileMenuText: {
      color: "text",
      fontSize: ["17px", "15px", "15px"],
    },
    profileMenuLink: {
      "&:hover": {
        backgroundColor: "dropdownMenuBackground",
        borderRadius: "5px",
      },
      // backgroundColor: "dropdownMenuBackground",
      textDecoration: "none",
      color: "text",
      padding: "5px",
      width: "100%",
      fontSize: ["17px", "15px", "15px"],
    },
  },
  buttons: {
    iconButton: {
      borderWidth: "0px",
      backgroundColor: "iconButtonBackground",
      "&:hover": { backgroundColor: "buttonBackgroundHoverColor" },
      width: "24px",
      height: "24px",
    },
    primaryButton: {
      backgroundColor: "text",
      color: "background",
      fontSize: "14px",
      paddingY: "6px",
      paddingX: ["20px", "10px", "10px"],
      lineHeight: "20px",
      fontWeight: "400",
      "&:hover": {
        backgroundColor: "primaryButtonBackgroundHover",
        cursor: "pointer",
      },
      "&:disabled": {
        backgroundColor: palette.grayMedium,
        cursor: "not-allowed",
      },
    },
    secondaryButton: {
      backgroundColor: "secondaryButtonBackground",
      color: "text",
      fontSize: "14px",
      fontWeight: "400",
      "&:hover": {
        backgroundColor: "secondaryButtonBackgroundHover",
      },
    },
    dangerButton: {
      paddingY: "6px",
      background: palette.grayLight,
      borderColor: palette.grayMedium,
      borderWidth: "1px",
      borderStyle: "solid",
      color: "red",
      fontSize: "15px",
      fontWeight: "600",
      "&:hover": {
        backgroundColor: palette.red,
        color: "white",
        borderColor: palette.red,
      },
    },
  },
  forms: {
    defaultInput: {
      borderColor: "inputBackgroundColor",
      "&:focus": {
        borderColor: "inputFocusBorderColor",
        outline: "none",
      },
      backgroundColor: "transparent",
      fontSize: "16px",
      padding: "10px",
    },
    errorInput: {
      borderColor: palette.red,
      "&:focus": {
        borderColor: "inputFocusBorderColor",
        outline: "none",
      },
      backgroundColor: "inputBackgroundColor",
      fontSize: "16px",
      padding: "10px",
    },
    defaultLabel: {
      fontSize: "15px",
      marginBottom: "5px",
      display: "block",
      width: "unset",
    },
  },
  fonts: {
    body: '"SF Pro Display", "Inter", system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", sans-serif',
    heading:
      'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", sans-serif',
    monospace: "Menlo, monospace",
  },
  fontSizes: [12, 14, 16, 20, 24, 32, 48, 64],
  fontWeights: {
    body: 400,
    heading: 700,
    bold: 700,
  },
  sizes: {
    container: {
      maxWidth: "1100px",
    },
  },
} as unknown as Theme;
