// src/utils/theme.ts
import { darken, lighten } from "@theme-ui/color";
import { Theme } from "theme-ui";

const palette = {
  white: "#ffffff",
  black: "#000000",
  grayLighter: "#f8f8f8",
  grayLight: "#f0f0f0",
  grayMediumLight: "#e0e0e0",
  grayMedium: "#cccccc",
  grayMediumDark: "#b3b3b3",
  grayDark: "#555555",
  grayDarker: "#3f3f3f",
  grayDarkest: "#1a1a1a",
  grayDarkness: "#292929",
  red: "#de4747",
  blue: "#3096f0",
  yellow: "#ffd700",
};

export { palette };

export default {
  useColorSchemeMediaQuery: true,
  colors: {
    primary: palette.black,
    secondary: palette.grayMedium,
    highlight: palette.yellow,
    background: palette.white,
    backgroundOpaque: "rgba(0, 0, 0, 0.7)",
    backgroundTransparent: "rgba(255, 255, 255, 0.1)",
    text: palette.black,
    muted: palette.grayDark,
    surface: palette.grayMediumLight,
    surfaceAccent: darken(palette.grayMediumLight, 0.1),
    accent: palette.blue,
    border: palette.grayMedium,
    disabledBackground: palette.grayMedium,
    disabledText: palette.grayMediumDark,
    success: "#28A745",
    error: "#DC3545",
    warning: "#FFC107",
    info: "#17A2B8",
    link: palette.grayDarker,
    shadow: "rgba(0, 0, 0, 0.1)",
    selectedBackground: palette.grayDark,
    selectedBackgroundText: palette.white,
    modes: {
      dark: {
        primary: palette.white,
        secondary: palette.grayDark,
        highlight: palette.yellow,
        background: palette.grayDarkest,
        backgroundOpaque: "rgba(0, 0, 0, 0.7)",
        backgroundTransparent: "rgba(255, 255, 255, 0.1)",
        text: palette.white,
        muted: palette.grayDark,
        surface: palette.grayDarkness,
        surfaceAccent: lighten(palette.grayDarkness, 0.1),
        link: palette.grayMedium,
        accent: palette.blue,
        border: palette.grayDark,
        disabledBackground: palette.grayDark,
        disabledText: palette.grayDark,
        shadow: "rgba(0, 0, 0, 0.1)",
        selectedBackground: palette.grayDark,
        selectedBackgroundText: palette.white,
      },
    },
  },
  messages: {
    default: {
      backgroundColor: "accent",
      borderLeftColor: "accent",
    },
  },
  text: {
    postHeaderType: {
      marginTop: "auto",
      width: "fit-content",
      backgroundColor: "text",
      color: "background",
      fontSize: "14px",
      fontWeight: "600",
    },
    postHeaderBackground: {
      width: ["fit-content", "100%", "100%"],
      marginX: ["10px", "0", "0"],
      bg: ["surface", "surface", "surface"],
      paddingY: ["10px", "20px", "20px"],
      paddingX: [0, "20px", "20px"],
      gap: "10px",
      flexDirection: "column",
      justifyContent: "center",
      alignContent: "center",
      position: "relative",
      borderBottomColor: "muted",
      borderBottomWidth: ["1px", 0, 0],
      borderBottomStyle: "solid",
      height: "100%",
      cursor: "text",
    },
    publicBlogTOCHeader: {
      textTransform: "uppercase",
      fontSize: "14px",
      fontWeight: 400,
      lineHeight: "20px",
      marginBottom: "16px",
      height: "48px",
      borderBottomColor: "border",
      borderBottomWidth: "1px",
      borderBottomStyle: "solid",
    },
    publicBlogHeaderText: {
      marginBottom: "16px",
      fontSize: ["33px", "40px", "46px"],
      fontWeight: 400,
      lineHeight: ["48px", "48px", "64px"],
      letterSpacing: "-2px",
    },
    publicBlogHeaderBack: {
      marginBottom: "58px",
      lineHeight: "34px",
      fontWeight: 400,
      fontSize: "26px",
      color: "muted",
    },
    publicBlogAuthorName: {
      fontWeight: "400",
      fontSize: "16px",
      lineHeight: "24px",
    },
    publicBlogHeaderExcerpt: {
      marginBottom: "30px",
      paddingTop: "16px",
      fontSize: "16px",
      lineHeight: "28px",
      fontWeight: 300,
    },
    publicHeaderDate: {
      fontWeight: "400",
      fontSize: "14px",
      lineHeight: "24px",
    },
    aboutHeader: {
      fontWeight: 400,
      fontSize: "40px",
      lineHeight: "48px",
      letterSpacing: "-1px",
      marginBottom: "16px",
    },
    aboutHeaderSmall: {
      fontWeight: 400,
      fontSize: "32px",
      lineHeight: "40px",
      letterSpacing: "-1px",
      marginBottom: "8px",
    },
    aboutParagraph: {
      marginBottom: "28px",
      paddingTop: "16px",
      fontSize: "16px",
      lineHeight: "28px",
      fontWeight: 300,
    },
    menuItem: {
      "&:hover": {
        backgroundColor: "accent",
        borderRadius: "5px",
      },
      cursor: "pointer",
      color: "text",
      width: "100%",
      fontSize: ["17px", "15px", "15px"],
      textDecoration: "none",
    },
    error: {
      color: palette.red,
      lineHeight: "24px",
      fontSize: "15px",
    },
  },
  boxes: {
    skeletonButton: {
      height: "32px",
      width: "32px",
      borderRadius: "5px",
    },
    publicMenuDropdown: {
      position: "absolute",
      width: "300px",
      padding: "20px",
      marginLeft: "-10px",
      borderRadius: "5px",
      backgroundColor: "background",
      borderColor: "border",
      borderWidth: "1px",
      borderStyle: "solid",
      boxShadow: "0 3px 8px rgba(0, 0, 0, 0.3)",
    },
    publicShareSection: {
      marginTop: "16px",
      gap: "16px",
      marginBottom: "200px",
      maxWidth: "1280px",
      marginX: ["16px", "16px", "16px"],
      borderTopColor: "border",
      borderTopStyle: "solid",
      borderTopWidth: "1px",
      paddingTop: "24px",
      flexDirection: ["column", "row", "row"],
    },
    menuItem: {
      padding: "5px",
      background: "background",
      borderColor: "border",
      borderWidth: "1px",
      borderStyle: "solid",
      borderRadius: "5px",
      zIndex: "4",
      boxShadow: "0 3px 8px rgba(0, 0, 0, 0.3)",
      animation: "fadeIn .2s;",
    },
    sidebarMenuItem: {
      fontSize: "15px",
      paddingY: "5px",
      borderRadius: "5px",
      width: "100%",
      "&:hover": {
        background: "surface",
        ".childButton": {
          transform: "scale(1.1)",
          transition: "background 0.5s, transform 0.5s ease-out, fill 0.5s",
        },
      },
    },
    componentCard: {
      maxWidth: "690px",
      borderColor: ["background", "background", "background"],
      borderRadius: ["0px", "5px", "5px"],
      position: "relative",
      marginY: ["0px", "20px", "20px"],
    },
    dropdownMenuItem: {
      padding: "10px",
      cursor: "pointer",
      "&:hover": {
        backgroundColor: "accent",
        borderRadius: "5px",
      },
    },
  },
  links: {
    mainMenuItem: {
      fontWeight: 600,
      padding: "5px",
      color: "text",
      "&:hover": {
        backgroundColor: "accent",
        borderRadius: "5px",
        color: "text",
      },
    },
    profileMenuText: {
      color: "text",
      fontSize: ["17px", "15px", "15px"],
    },
    profileMenuLink: {
      "&:hover": {
        backgroundColor: "background",
        borderRadius: "5px",
      },
      backgroundColor: "background",
      textDecoration: "none",
      color: "text",
      padding: "5px",
      width: "100%",
      fontSize: ["17px", "15px", "15px"],
    },
  },
  buttons: {
    iconButton: {
      borderWidth: "0px",
      backgroundColor: "primary",
      "&:hover": { backgroundColor: "accent" },
      width: "24px",
      height: "24px",
    },
    primaryButton: {
      backgroundColor: "text",
      color: "background",
      fontSize: "14px",
      paddingY: "6px",
      paddingX: ["20px", "10px", "10px"],
      lineHeight: "20px",
      fontWeight: "400",
      "&:hover": {
        backgroundColor: "accent",
        cursor: "pointer",
      },
      "&:disabled": {
        backgroundColor: palette.grayMedium,
        cursor: "not-allowed",
      },
    },
    secondaryButton: {
      backgroundColor: "secondary",
      color: "text",
      fontWeight: "400",
      "&:hover": {
        backgroundColor: darken("secondary", 0.1),
      },
    },
    dangerButton: {
      paddingY: "6px",
      background: "danger",
      borderColor: "danger",
      borderWidth: "1px",
      borderStyle: "solid",
      color: "red",
      fontSize: "15px",
      fontWeight: "600",
      "&:hover": {
        backgroundColor: "danger",
        color: "white",
        borderColor: "danger",
      },
    },
  },
  forms: {
    defaultInput: {
      borderColor: "surface",
      "&:focus": {
        borderColor: "accent",
        outline: "none",
      },
      backgroundColor: "surface",
      fontSize: "16px",
      padding: "10px",
    },
    errorInput: {
      borderColor: palette.red,
      "&:focus": {
        borderColor: "border",
        outline: "none",
      },
      backgroundColor: "surface",
      fontSize: "16px",
      padding: "10px",
    },
    defaultLabel: {
      fontSize: "15px",
      marginBottom: "5px",
      display: "block",
      width: "unset",
    },
  },
  fonts: {
    body: '"SF Pro Display", "Inter", system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", sans-serif',
    heading:
      'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", sans-serif',
    monospace: "Menlo, monospace",
  },
  fontSizes: [12, 14, 16, 20, 24, 32, 48, 64],
  fontWeights: {
    body: 400,
    heading: 700,
    bold: 700,
  },
  sizes: {
    container: {
      maxWidth: "1100px",
    },
  },
} as unknown as Theme;
