/* tslint:disable */
/* eslint-disable */
//  This file was automatically generated and should not be edited.

export type UpdatePostInput = {
  id: string,
  title?: string | null,
  gpxFile?: string | null,
  images?: string | null,
  headerImage?: string | null,
  date?: string | null,
  publishedDate?: string | null,
  location?: string | null,
  postLocation?: string | null,
  stravaUrl?: string | null,
  resultsUrl?: string | null,
  type?: string | null,
  subType?: string | null,
  teaser?: string | null,
  currentFtp?: string | null,
  components?: string | null,
  powerAnalysis?: string | null,
  coordinates?: string | null,
  powers?: string | null,
  elevation?: string | null,
  elevationGrades?: string | null,
  distances?: string | null,
  blogPostsId?: string | null,
  postRelatedId?: string | null,
  postAuthorId?: string | null,
};

export type ModelPostConditionInput = {
  title?: ModelStringInput | null,
  gpxFile?: ModelStringInput | null,
  images?: ModelStringInput | null,
  headerImage?: ModelStringInput | null,
  date?: ModelStringInput | null,
  publishedDate?: ModelStringInput | null,
  location?: ModelStringInput | null,
  postLocation?: ModelStringInput | null,
  stravaUrl?: ModelStringInput | null,
  resultsUrl?: ModelStringInput | null,
  type?: ModelStringInput | null,
  subType?: ModelStringInput | null,
  teaser?: ModelStringInput | null,
  currentFtp?: ModelStringInput | null,
  components?: ModelStringInput | null,
  powerAnalysis?: ModelStringInput | null,
  coordinates?: ModelStringInput | null,
  powers?: ModelStringInput | null,
  elevation?: ModelStringInput | null,
  elevationGrades?: ModelStringInput | null,
  distances?: ModelStringInput | null,
  and?: Array< ModelPostConditionInput | null > | null,
  or?: Array< ModelPostConditionInput | null > | null,
  not?: ModelPostConditionInput | null,
  blogPostsId?: ModelIDInput | null,
  postRelatedId?: ModelIDInput | null,
  postAuthorId?: ModelIDInput | null,
};

export type ModelStringInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export enum ModelAttributeTypes {
  binary = "binary",
  binarySet = "binarySet",
  bool = "bool",
  list = "list",
  map = "map",
  number = "number",
  numberSet = "numberSet",
  string = "string",
  stringSet = "stringSet",
  _null = "_null",
}


export type ModelSizeInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
};

export type ModelIDInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export type Post = {
  __typename: "Post",
  id: string,
  title: string,
  gpxFile?: string | null,
  images?: string | null,
  headerImage?: string | null,
  date?: string | null,
  publishedDate?: string | null,
  location?: string | null,
  postLocation?: string | null,
  stravaUrl?: string | null,
  resultsUrl?: string | null,
  type?: string | null,
  subType?: string | null,
  teaser?: string | null,
  currentFtp?: string | null,
  components?: string | null,
  powerAnalysis?: string | null,
  coordinates?: string | null,
  powers?: string | null,
  elevation?: string | null,
  elevationGrades?: string | null,
  distances?: string | null,
  blog?: Blog | null,
  related?: ModelPostConnection | null,
  author?: User | null,
  createdAt: string,
  updatedAt: string,
  blogPostsId?: string | null,
  postRelatedId?: string | null,
  postAuthorId?: string | null,
  owner?: string | null,
};

export type Blog = {
  __typename: "Blog",
  id: string,
  name: string,
  posts?: ModelPostConnection | null,
  createdAt: string,
  updatedAt: string,
  owner?: string | null,
};

export type ModelPostConnection = {
  __typename: "ModelPostConnection",
  items:  Array<Post | null >,
  nextToken?: string | null,
};

export type User = {
  __typename: "User",
  id: string,
  fullName: string,
  email: string,
  image?: string | null,
  username?: string | null,
  createdAt: string,
  updatedAt: string,
  owner?: string | null,
};

export type ModelPostFilterInput = {
  id?: ModelIDInput | null,
  title?: ModelStringInput | null,
  gpxFile?: ModelStringInput | null,
  images?: ModelStringInput | null,
  headerImage?: ModelStringInput | null,
  date?: ModelStringInput | null,
  publishedDate?: ModelStringInput | null,
  location?: ModelStringInput | null,
  postLocation?: ModelStringInput | null,
  stravaUrl?: ModelStringInput | null,
  resultsUrl?: ModelStringInput | null,
  type?: ModelStringInput | null,
  subType?: ModelStringInput | null,
  teaser?: ModelStringInput | null,
  currentFtp?: ModelStringInput | null,
  components?: ModelStringInput | null,
  powerAnalysis?: ModelStringInput | null,
  coordinates?: ModelStringInput | null,
  powers?: ModelStringInput | null,
  elevation?: ModelStringInput | null,
  elevationGrades?: ModelStringInput | null,
  distances?: ModelStringInput | null,
  and?: Array< ModelPostFilterInput | null > | null,
  or?: Array< ModelPostFilterInput | null > | null,
  not?: ModelPostFilterInput | null,
  blogPostsId?: ModelIDInput | null,
  postRelatedId?: ModelIDInput | null,
  postAuthorId?: ModelIDInput | null,
};

export type CreateUserInput = {
  id?: string | null,
  fullName: string,
  email: string,
  image?: string | null,
  username?: string | null,
};

export type ModelUserConditionInput = {
  fullName?: ModelStringInput | null,
  email?: ModelStringInput | null,
  image?: ModelStringInput | null,
  username?: ModelStringInput | null,
  and?: Array< ModelUserConditionInput | null > | null,
  or?: Array< ModelUserConditionInput | null > | null,
  not?: ModelUserConditionInput | null,
};

export type UpdateUserInput = {
  id: string,
  fullName?: string | null,
  email?: string | null,
  image?: string | null,
  username?: string | null,
};

export type DeleteUserInput = {
  id: string,
};

export type CreateBlogInput = {
  id?: string | null,
  name: string,
};

export type ModelBlogConditionInput = {
  name?: ModelStringInput | null,
  and?: Array< ModelBlogConditionInput | null > | null,
  or?: Array< ModelBlogConditionInput | null > | null,
  not?: ModelBlogConditionInput | null,
};

export type UpdateBlogInput = {
  id: string,
  name?: string | null,
};

export type DeleteBlogInput = {
  id: string,
};

export type CreatePostInput = {
  id?: string | null,
  title: string,
  gpxFile?: string | null,
  images?: string | null,
  headerImage?: string | null,
  date?: string | null,
  publishedDate?: string | null,
  location?: string | null,
  postLocation?: string | null,
  stravaUrl?: string | null,
  resultsUrl?: string | null,
  type?: string | null,
  subType?: string | null,
  teaser?: string | null,
  currentFtp?: string | null,
  components?: string | null,
  powerAnalysis?: string | null,
  coordinates?: string | null,
  powers?: string | null,
  elevation?: string | null,
  elevationGrades?: string | null,
  distances?: string | null,
  blogPostsId?: string | null,
  postRelatedId?: string | null,
  postAuthorId?: string | null,
};

export type DeletePostInput = {
  id: string,
};

export type ModelUserFilterInput = {
  id?: ModelIDInput | null,
  fullName?: ModelStringInput | null,
  email?: ModelStringInput | null,
  image?: ModelStringInput | null,
  username?: ModelStringInput | null,
  and?: Array< ModelUserFilterInput | null > | null,
  or?: Array< ModelUserFilterInput | null > | null,
  not?: ModelUserFilterInput | null,
};

export type ModelUserConnection = {
  __typename: "ModelUserConnection",
  items:  Array<User | null >,
  nextToken?: string | null,
};

export type ModelBlogFilterInput = {
  id?: ModelIDInput | null,
  name?: ModelStringInput | null,
  and?: Array< ModelBlogFilterInput | null > | null,
  or?: Array< ModelBlogFilterInput | null > | null,
  not?: ModelBlogFilterInput | null,
};

export type ModelBlogConnection = {
  __typename: "ModelBlogConnection",
  items:  Array<Blog | null >,
  nextToken?: string | null,
};

export type ModelSubscriptionUserFilterInput = {
  id?: ModelSubscriptionIDInput | null,
  fullName?: ModelSubscriptionStringInput | null,
  email?: ModelSubscriptionStringInput | null,
  image?: ModelSubscriptionStringInput | null,
  username?: ModelSubscriptionStringInput | null,
  and?: Array< ModelSubscriptionUserFilterInput | null > | null,
  or?: Array< ModelSubscriptionUserFilterInput | null > | null,
};

export type ModelSubscriptionIDInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  in?: Array< string | null > | null,
  notIn?: Array< string | null > | null,
};

export type ModelSubscriptionStringInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  in?: Array< string | null > | null,
  notIn?: Array< string | null > | null,
};

export type ModelSubscriptionBlogFilterInput = {
  id?: ModelSubscriptionIDInput | null,
  name?: ModelSubscriptionStringInput | null,
  and?: Array< ModelSubscriptionBlogFilterInput | null > | null,
  or?: Array< ModelSubscriptionBlogFilterInput | null > | null,
};

export type ModelSubscriptionPostFilterInput = {
  id?: ModelSubscriptionIDInput | null,
  title?: ModelSubscriptionStringInput | null,
  gpxFile?: ModelSubscriptionStringInput | null,
  images?: ModelSubscriptionStringInput | null,
  headerImage?: ModelSubscriptionStringInput | null,
  date?: ModelSubscriptionStringInput | null,
  publishedDate?: ModelSubscriptionStringInput | null,
  location?: ModelSubscriptionStringInput | null,
  postLocation?: ModelSubscriptionStringInput | null,
  stravaUrl?: ModelSubscriptionStringInput | null,
  resultsUrl?: ModelSubscriptionStringInput | null,
  type?: ModelSubscriptionStringInput | null,
  subType?: ModelSubscriptionStringInput | null,
  teaser?: ModelSubscriptionStringInput | null,
  currentFtp?: ModelSubscriptionStringInput | null,
  components?: ModelSubscriptionStringInput | null,
  powerAnalysis?: ModelSubscriptionStringInput | null,
  coordinates?: ModelSubscriptionStringInput | null,
  powers?: ModelSubscriptionStringInput | null,
  elevation?: ModelSubscriptionStringInput | null,
  elevationGrades?: ModelSubscriptionStringInput | null,
  distances?: ModelSubscriptionStringInput | null,
  and?: Array< ModelSubscriptionPostFilterInput | null > | null,
  or?: Array< ModelSubscriptionPostFilterInput | null > | null,
};

export type UpdatePostMinimalMutationVariables = {
  input: UpdatePostInput,
  condition?: ModelPostConditionInput | null,
};

export type UpdatePostMinimalMutation = {
  updatePost?:  {
    __typename: "Post",
    id: string,
    title: string,
    gpxFile?: string | null,
    images?: string | null,
    headerImage?: string | null,
    date?: string | null,
    publishedDate?: string | null,
    location?: string | null,
    postLocation?: string | null,
    stravaUrl?: string | null,
    resultsUrl?: string | null,
    type?: string | null,
    subType?: string | null,
    teaser?: string | null,
    currentFtp?: string | null,
    components?: string | null,
    blog?:  {
      __typename: "Blog",
      id: string,
      name: string,
      posts?:  {
        __typename: "ModelPostConnection",
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      owner?: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    blogPostsId?: string | null,
    postRelatedId?: string | null,
    owner?: string | null,
  } | null,
};

export type GetActivityQueryQueryVariables = {
  id: string,
};

export type GetActivityQueryQuery = {
  getPost?:  {
    __typename: "Post",
    powerAnalysis?: string | null,
    coordinates?: string | null,
    powers?: string | null,
    elevation?: string | null,
    elevationGrades?: string | null,
    distances?: string | null,
  } | null,
};

export type GetPostInitialQueryVariables = {
  id: string,
};

export type GetPostInitialQuery = {
  getPost?:  {
    __typename: "Post",
    id: string,
    title: string,
    gpxFile?: string | null,
    images?: string | null,
    headerImage?: string | null,
    date?: string | null,
    publishedDate?: string | null,
    location?: string | null,
    postLocation?: string | null,
    stravaUrl?: string | null,
    resultsUrl?: string | null,
    type?: string | null,
    subType?: string | null,
    teaser?: string | null,
    currentFtp?: string | null,
    components?: string | null,
    blog?:  {
      __typename: "Blog",
      id: string,
      name: string,
      posts?:  {
        __typename: "ModelPostConnection",
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      owner?: string | null,
    } | null,
    author?:  {
      __typename: "User",
      id: string,
      fullName: string,
      email: string,
      image?: string | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    createdAt: string,
    updatedAt: string,
    blogPostsId?: string | null,
    postRelatedId?: string | null,
  } | null,
};

export type listPostsCustomQueryVariables = {
  filter?: ModelPostFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type listPostsCustomQuery = {
  listPosts?:  {
    __typename: "ModelPostConnection",
    items:  Array< {
      __typename: "Post",
      id: string,
      title: string,
      gpxFile?: string | null,
      images?: string | null,
      headerImage?: string | null,
      date?: string | null,
      publishedDate?: string | null,
      location?: string | null,
      postLocation?: string | null,
      stravaUrl?: string | null,
      resultsUrl?: string | null,
      type?: string | null,
      subType?: string | null,
      teaser?: string | null,
      currentFtp?: string | null,
      postAuthorId?: string | null,
      author?:  {
        __typename: "User",
        id: string,
        fullName: string,
        email: string,
        image?: string | null,
        username?: string | null,
      } | null,
      related?:  {
        __typename: "ModelPostConnection",
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      blogPostsId?: string | null,
      postRelatedId?: string | null,
    } | null >,
    nextToken?: string | null,
  } | null,
};

export type CreateUserMutationVariables = {
  input: CreateUserInput,
  condition?: ModelUserConditionInput | null,
};

export type CreateUserMutation = {
  createUser?:  {
    __typename: "User",
    id: string,
    fullName: string,
    email: string,
    image?: string | null,
    username?: string | null,
    createdAt: string,
    updatedAt: string,
    owner?: string | null,
  } | null,
};

export type UpdateUserMutationVariables = {
  input: UpdateUserInput,
  condition?: ModelUserConditionInput | null,
};

export type UpdateUserMutation = {
  updateUser?:  {
    __typename: "User",
    id: string,
    fullName: string,
    email: string,
    image?: string | null,
    username?: string | null,
    createdAt: string,
    updatedAt: string,
    owner?: string | null,
  } | null,
};

export type DeleteUserMutationVariables = {
  input: DeleteUserInput,
  condition?: ModelUserConditionInput | null,
};

export type DeleteUserMutation = {
  deleteUser?:  {
    __typename: "User",
    id: string,
    fullName: string,
    email: string,
    image?: string | null,
    username?: string | null,
    createdAt: string,
    updatedAt: string,
    owner?: string | null,
  } | null,
};

export type CreateBlogMutationVariables = {
  input: CreateBlogInput,
  condition?: ModelBlogConditionInput | null,
};

export type CreateBlogMutation = {
  createBlog?:  {
    __typename: "Blog",
    id: string,
    name: string,
    posts?:  {
      __typename: "ModelPostConnection",
      items:  Array< {
        __typename: "Post",
        id: string,
        title: string,
        gpxFile?: string | null,
        images?: string | null,
        headerImage?: string | null,
        date?: string | null,
        publishedDate?: string | null,
        location?: string | null,
        postLocation?: string | null,
        stravaUrl?: string | null,
        resultsUrl?: string | null,
        type?: string | null,
        subType?: string | null,
        teaser?: string | null,
        currentFtp?: string | null,
        components?: string | null,
        powerAnalysis?: string | null,
        coordinates?: string | null,
        powers?: string | null,
        elevation?: string | null,
        elevationGrades?: string | null,
        distances?: string | null,
        createdAt: string,
        updatedAt: string,
        blogPostsId?: string | null,
        postRelatedId?: string | null,
        postAuthorId?: string | null,
        owner?: string | null,
      } | null >,
      nextToken?: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    owner?: string | null,
  } | null,
};

export type UpdateBlogMutationVariables = {
  input: UpdateBlogInput,
  condition?: ModelBlogConditionInput | null,
};

export type UpdateBlogMutation = {
  updateBlog?:  {
    __typename: "Blog",
    id: string,
    name: string,
    posts?:  {
      __typename: "ModelPostConnection",
      items:  Array< {
        __typename: "Post",
        id: string,
        title: string,
        gpxFile?: string | null,
        images?: string | null,
        headerImage?: string | null,
        date?: string | null,
        publishedDate?: string | null,
        location?: string | null,
        postLocation?: string | null,
        stravaUrl?: string | null,
        resultsUrl?: string | null,
        type?: string | null,
        subType?: string | null,
        teaser?: string | null,
        currentFtp?: string | null,
        components?: string | null,
        powerAnalysis?: string | null,
        coordinates?: string | null,
        powers?: string | null,
        elevation?: string | null,
        elevationGrades?: string | null,
        distances?: string | null,
        createdAt: string,
        updatedAt: string,
        blogPostsId?: string | null,
        postRelatedId?: string | null,
        postAuthorId?: string | null,
        owner?: string | null,
      } | null >,
      nextToken?: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    owner?: string | null,
  } | null,
};

export type DeleteBlogMutationVariables = {
  input: DeleteBlogInput,
  condition?: ModelBlogConditionInput | null,
};

export type DeleteBlogMutation = {
  deleteBlog?:  {
    __typename: "Blog",
    id: string,
    name: string,
    posts?:  {
      __typename: "ModelPostConnection",
      items:  Array< {
        __typename: "Post",
        id: string,
        title: string,
        gpxFile?: string | null,
        images?: string | null,
        headerImage?: string | null,
        date?: string | null,
        publishedDate?: string | null,
        location?: string | null,
        postLocation?: string | null,
        stravaUrl?: string | null,
        resultsUrl?: string | null,
        type?: string | null,
        subType?: string | null,
        teaser?: string | null,
        currentFtp?: string | null,
        components?: string | null,
        powerAnalysis?: string | null,
        coordinates?: string | null,
        powers?: string | null,
        elevation?: string | null,
        elevationGrades?: string | null,
        distances?: string | null,
        createdAt: string,
        updatedAt: string,
        blogPostsId?: string | null,
        postRelatedId?: string | null,
        postAuthorId?: string | null,
        owner?: string | null,
      } | null >,
      nextToken?: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    owner?: string | null,
  } | null,
};

export type CreatePostMutationVariables = {
  input: CreatePostInput,
  condition?: ModelPostConditionInput | null,
};

export type CreatePostMutation = {
  createPost?:  {
    __typename: "Post",
    id: string,
    title: string,
    gpxFile?: string | null,
    images?: string | null,
    headerImage?: string | null,
    date?: string | null,
    publishedDate?: string | null,
    location?: string | null,
    postLocation?: string | null,
    stravaUrl?: string | null,
    resultsUrl?: string | null,
    type?: string | null,
    subType?: string | null,
    teaser?: string | null,
    currentFtp?: string | null,
    components?: string | null,
    powerAnalysis?: string | null,
    coordinates?: string | null,
    powers?: string | null,
    elevation?: string | null,
    elevationGrades?: string | null,
    distances?: string | null,
    blog?:  {
      __typename: "Blog",
      id: string,
      name: string,
      posts?:  {
        __typename: "ModelPostConnection",
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      owner?: string | null,
    } | null,
    related?:  {
      __typename: "ModelPostConnection",
      items:  Array< {
        __typename: "Post",
        id: string,
        title: string,
        gpxFile?: string | null,
        images?: string | null,
        headerImage?: string | null,
        date?: string | null,
        publishedDate?: string | null,
        location?: string | null,
        postLocation?: string | null,
        stravaUrl?: string | null,
        resultsUrl?: string | null,
        type?: string | null,
        subType?: string | null,
        teaser?: string | null,
        currentFtp?: string | null,
        components?: string | null,
        powerAnalysis?: string | null,
        coordinates?: string | null,
        powers?: string | null,
        elevation?: string | null,
        elevationGrades?: string | null,
        distances?: string | null,
        createdAt: string,
        updatedAt: string,
        blogPostsId?: string | null,
        postRelatedId?: string | null,
        postAuthorId?: string | null,
        owner?: string | null,
      } | null >,
      nextToken?: string | null,
    } | null,
    author?:  {
      __typename: "User",
      id: string,
      fullName: string,
      email: string,
      image?: string | null,
      username?: string | null,
      createdAt: string,
      updatedAt: string,
      owner?: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    blogPostsId?: string | null,
    postRelatedId?: string | null,
    postAuthorId?: string | null,
    owner?: string | null,
  } | null,
};

export type UpdatePostMutationVariables = {
  input: UpdatePostInput,
  condition?: ModelPostConditionInput | null,
};

export type UpdatePostMutation = {
  updatePost?:  {
    __typename: "Post",
    id: string,
    title: string,
    gpxFile?: string | null,
    images?: string | null,
    headerImage?: string | null,
    date?: string | null,
    publishedDate?: string | null,
    location?: string | null,
    postLocation?: string | null,
    stravaUrl?: string | null,
    resultsUrl?: string | null,
    type?: string | null,
    subType?: string | null,
    teaser?: string | null,
    currentFtp?: string | null,
    components?: string | null,
    powerAnalysis?: string | null,
    coordinates?: string | null,
    powers?: string | null,
    elevation?: string | null,
    elevationGrades?: string | null,
    distances?: string | null,
    blog?:  {
      __typename: "Blog",
      id: string,
      name: string,
      posts?:  {
        __typename: "ModelPostConnection",
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      owner?: string | null,
    } | null,
    related?:  {
      __typename: "ModelPostConnection",
      items:  Array< {
        __typename: "Post",
        id: string,
        title: string,
        gpxFile?: string | null,
        images?: string | null,
        headerImage?: string | null,
        date?: string | null,
        publishedDate?: string | null,
        location?: string | null,
        postLocation?: string | null,
        stravaUrl?: string | null,
        resultsUrl?: string | null,
        type?: string | null,
        subType?: string | null,
        teaser?: string | null,
        currentFtp?: string | null,
        components?: string | null,
        powerAnalysis?: string | null,
        coordinates?: string | null,
        powers?: string | null,
        elevation?: string | null,
        elevationGrades?: string | null,
        distances?: string | null,
        createdAt: string,
        updatedAt: string,
        blogPostsId?: string | null,
        postRelatedId?: string | null,
        postAuthorId?: string | null,
        owner?: string | null,
      } | null >,
      nextToken?: string | null,
    } | null,
    author?:  {
      __typename: "User",
      id: string,
      fullName: string,
      email: string,
      image?: string | null,
      username?: string | null,
      createdAt: string,
      updatedAt: string,
      owner?: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    blogPostsId?: string | null,
    postRelatedId?: string | null,
    postAuthorId?: string | null,
    owner?: string | null,
  } | null,
};

export type DeletePostMutationVariables = {
  input: DeletePostInput,
  condition?: ModelPostConditionInput | null,
};

export type DeletePostMutation = {
  deletePost?:  {
    __typename: "Post",
    id: string,
    title: string,
    gpxFile?: string | null,
    images?: string | null,
    headerImage?: string | null,
    date?: string | null,
    publishedDate?: string | null,
    location?: string | null,
    postLocation?: string | null,
    stravaUrl?: string | null,
    resultsUrl?: string | null,
    type?: string | null,
    subType?: string | null,
    teaser?: string | null,
    currentFtp?: string | null,
    components?: string | null,
    powerAnalysis?: string | null,
    coordinates?: string | null,
    powers?: string | null,
    elevation?: string | null,
    elevationGrades?: string | null,
    distances?: string | null,
    blog?:  {
      __typename: "Blog",
      id: string,
      name: string,
      posts?:  {
        __typename: "ModelPostConnection",
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      owner?: string | null,
    } | null,
    related?:  {
      __typename: "ModelPostConnection",
      items:  Array< {
        __typename: "Post",
        id: string,
        title: string,
        gpxFile?: string | null,
        images?: string | null,
        headerImage?: string | null,
        date?: string | null,
        publishedDate?: string | null,
        location?: string | null,
        postLocation?: string | null,
        stravaUrl?: string | null,
        resultsUrl?: string | null,
        type?: string | null,
        subType?: string | null,
        teaser?: string | null,
        currentFtp?: string | null,
        components?: string | null,
        powerAnalysis?: string | null,
        coordinates?: string | null,
        powers?: string | null,
        elevation?: string | null,
        elevationGrades?: string | null,
        distances?: string | null,
        createdAt: string,
        updatedAt: string,
        blogPostsId?: string | null,
        postRelatedId?: string | null,
        postAuthorId?: string | null,
        owner?: string | null,
      } | null >,
      nextToken?: string | null,
    } | null,
    author?:  {
      __typename: "User",
      id: string,
      fullName: string,
      email: string,
      image?: string | null,
      username?: string | null,
      createdAt: string,
      updatedAt: string,
      owner?: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    blogPostsId?: string | null,
    postRelatedId?: string | null,
    postAuthorId?: string | null,
    owner?: string | null,
  } | null,
};

export type GetUserQueryVariables = {
  id: string,
};

export type GetUserQuery = {
  getUser?:  {
    __typename: "User",
    id: string,
    fullName: string,
    email: string,
    image?: string | null,
    username?: string | null,
    createdAt: string,
    updatedAt: string,
    owner?: string | null,
  } | null,
};

export type ListUsersQueryVariables = {
  filter?: ModelUserFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListUsersQuery = {
  listUsers?:  {
    __typename: "ModelUserConnection",
    items:  Array< {
      __typename: "User",
      id: string,
      fullName: string,
      email: string,
      image?: string | null,
      username?: string | null,
      createdAt: string,
      updatedAt: string,
      owner?: string | null,
    } | null >,
    nextToken?: string | null,
  } | null,
};

export type GetBlogQueryVariables = {
  id: string,
};

export type GetBlogQuery = {
  getBlog?:  {
    __typename: "Blog",
    id: string,
    name: string,
    posts?:  {
      __typename: "ModelPostConnection",
      items:  Array< {
        __typename: "Post",
        id: string,
        title: string,
        gpxFile?: string | null,
        images?: string | null,
        headerImage?: string | null,
        date?: string | null,
        publishedDate?: string | null,
        location?: string | null,
        postLocation?: string | null,
        stravaUrl?: string | null,
        resultsUrl?: string | null,
        type?: string | null,
        subType?: string | null,
        teaser?: string | null,
        currentFtp?: string | null,
        components?: string | null,
        powerAnalysis?: string | null,
        coordinates?: string | null,
        powers?: string | null,
        elevation?: string | null,
        elevationGrades?: string | null,
        distances?: string | null,
        createdAt: string,
        updatedAt: string,
        blogPostsId?: string | null,
        postRelatedId?: string | null,
        postAuthorId?: string | null,
        owner?: string | null,
      } | null >,
      nextToken?: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    owner?: string | null,
  } | null,
};

export type ListBlogsQueryVariables = {
  filter?: ModelBlogFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListBlogsQuery = {
  listBlogs?:  {
    __typename: "ModelBlogConnection",
    items:  Array< {
      __typename: "Blog",
      id: string,
      name: string,
      posts?:  {
        __typename: "ModelPostConnection",
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      owner?: string | null,
    } | null >,
    nextToken?: string | null,
  } | null,
};

export type GetPostQueryVariables = {
  id: string,
};

export type GetPostQuery = {
  getPost?:  {
    __typename: "Post",
    id: string,
    title: string,
    gpxFile?: string | null,
    images?: string | null,
    headerImage?: string | null,
    date?: string | null,
    publishedDate?: string | null,
    location?: string | null,
    postLocation?: string | null,
    stravaUrl?: string | null,
    resultsUrl?: string | null,
    type?: string | null,
    subType?: string | null,
    teaser?: string | null,
    currentFtp?: string | null,
    components?: string | null,
    powerAnalysis?: string | null,
    coordinates?: string | null,
    powers?: string | null,
    elevation?: string | null,
    elevationGrades?: string | null,
    distances?: string | null,
    blog?:  {
      __typename: "Blog",
      id: string,
      name: string,
      posts?:  {
        __typename: "ModelPostConnection",
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      owner?: string | null,
    } | null,
    related?:  {
      __typename: "ModelPostConnection",
      items:  Array< {
        __typename: "Post",
        id: string,
        title: string,
        gpxFile?: string | null,
        images?: string | null,
        headerImage?: string | null,
        date?: string | null,
        publishedDate?: string | null,
        location?: string | null,
        postLocation?: string | null,
        stravaUrl?: string | null,
        resultsUrl?: string | null,
        type?: string | null,
        subType?: string | null,
        teaser?: string | null,
        currentFtp?: string | null,
        components?: string | null,
        powerAnalysis?: string | null,
        coordinates?: string | null,
        powers?: string | null,
        elevation?: string | null,
        elevationGrades?: string | null,
        distances?: string | null,
        createdAt: string,
        updatedAt: string,
        blogPostsId?: string | null,
        postRelatedId?: string | null,
        postAuthorId?: string | null,
        owner?: string | null,
      } | null >,
      nextToken?: string | null,
    } | null,
    author?:  {
      __typename: "User",
      id: string,
      fullName: string,
      email: string,
      image?: string | null,
      username?: string | null,
      createdAt: string,
      updatedAt: string,
      owner?: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    blogPostsId?: string | null,
    postRelatedId?: string | null,
    postAuthorId?: string | null,
    owner?: string | null,
  } | null,
};

export type ListPostsQueryVariables = {
  filter?: ModelPostFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListPostsQuery = {
  listPosts?:  {
    __typename: "ModelPostConnection",
    items:  Array< {
      __typename: "Post",
      id: string,
      title: string,
      gpxFile?: string | null,
      images?: string | null,
      headerImage?: string | null,
      date?: string | null,
      publishedDate?: string | null,
      location?: string | null,
      postLocation?: string | null,
      stravaUrl?: string | null,
      resultsUrl?: string | null,
      type?: string | null,
      subType?: string | null,
      teaser?: string | null,
      currentFtp?: string | null,
      components?: string | null,
      powerAnalysis?: string | null,
      coordinates?: string | null,
      powers?: string | null,
      elevation?: string | null,
      elevationGrades?: string | null,
      distances?: string | null,
      blog?:  {
        __typename: "Blog",
        id: string,
        name: string,
        createdAt: string,
        updatedAt: string,
        owner?: string | null,
      } | null,
      related?:  {
        __typename: "ModelPostConnection",
        nextToken?: string | null,
      } | null,
      author?:  {
        __typename: "User",
        id: string,
        fullName: string,
        email: string,
        image?: string | null,
        username?: string | null,
        createdAt: string,
        updatedAt: string,
        owner?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      blogPostsId?: string | null,
      postRelatedId?: string | null,
      postAuthorId?: string | null,
      owner?: string | null,
    } | null >,
    nextToken?: string | null,
  } | null,
};

export type OnCreateUserSubscriptionVariables = {
  filter?: ModelSubscriptionUserFilterInput | null,
  owner?: string | null,
};

export type OnCreateUserSubscription = {
  onCreateUser?:  {
    __typename: "User",
    id: string,
    fullName: string,
    email: string,
    image?: string | null,
    username?: string | null,
    createdAt: string,
    updatedAt: string,
    owner?: string | null,
  } | null,
};

export type OnUpdateUserSubscriptionVariables = {
  filter?: ModelSubscriptionUserFilterInput | null,
  owner?: string | null,
};

export type OnUpdateUserSubscription = {
  onUpdateUser?:  {
    __typename: "User",
    id: string,
    fullName: string,
    email: string,
    image?: string | null,
    username?: string | null,
    createdAt: string,
    updatedAt: string,
    owner?: string | null,
  } | null,
};

export type OnDeleteUserSubscriptionVariables = {
  filter?: ModelSubscriptionUserFilterInput | null,
  owner?: string | null,
};

export type OnDeleteUserSubscription = {
  onDeleteUser?:  {
    __typename: "User",
    id: string,
    fullName: string,
    email: string,
    image?: string | null,
    username?: string | null,
    createdAt: string,
    updatedAt: string,
    owner?: string | null,
  } | null,
};

export type OnCreateBlogSubscriptionVariables = {
  filter?: ModelSubscriptionBlogFilterInput | null,
  owner?: string | null,
};

export type OnCreateBlogSubscription = {
  onCreateBlog?:  {
    __typename: "Blog",
    id: string,
    name: string,
    posts?:  {
      __typename: "ModelPostConnection",
      items:  Array< {
        __typename: "Post",
        id: string,
        title: string,
        gpxFile?: string | null,
        images?: string | null,
        headerImage?: string | null,
        date?: string | null,
        publishedDate?: string | null,
        location?: string | null,
        postLocation?: string | null,
        stravaUrl?: string | null,
        resultsUrl?: string | null,
        type?: string | null,
        subType?: string | null,
        teaser?: string | null,
        currentFtp?: string | null,
        components?: string | null,
        powerAnalysis?: string | null,
        coordinates?: string | null,
        powers?: string | null,
        elevation?: string | null,
        elevationGrades?: string | null,
        distances?: string | null,
        createdAt: string,
        updatedAt: string,
        blogPostsId?: string | null,
        postRelatedId?: string | null,
        postAuthorId?: string | null,
        owner?: string | null,
      } | null >,
      nextToken?: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    owner?: string | null,
  } | null,
};

export type OnUpdateBlogSubscriptionVariables = {
  filter?: ModelSubscriptionBlogFilterInput | null,
  owner?: string | null,
};

export type OnUpdateBlogSubscription = {
  onUpdateBlog?:  {
    __typename: "Blog",
    id: string,
    name: string,
    posts?:  {
      __typename: "ModelPostConnection",
      items:  Array< {
        __typename: "Post",
        id: string,
        title: string,
        gpxFile?: string | null,
        images?: string | null,
        headerImage?: string | null,
        date?: string | null,
        publishedDate?: string | null,
        location?: string | null,
        postLocation?: string | null,
        stravaUrl?: string | null,
        resultsUrl?: string | null,
        type?: string | null,
        subType?: string | null,
        teaser?: string | null,
        currentFtp?: string | null,
        components?: string | null,
        powerAnalysis?: string | null,
        coordinates?: string | null,
        powers?: string | null,
        elevation?: string | null,
        elevationGrades?: string | null,
        distances?: string | null,
        createdAt: string,
        updatedAt: string,
        blogPostsId?: string | null,
        postRelatedId?: string | null,
        postAuthorId?: string | null,
        owner?: string | null,
      } | null >,
      nextToken?: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    owner?: string | null,
  } | null,
};

export type OnDeleteBlogSubscriptionVariables = {
  filter?: ModelSubscriptionBlogFilterInput | null,
  owner?: string | null,
};

export type OnDeleteBlogSubscription = {
  onDeleteBlog?:  {
    __typename: "Blog",
    id: string,
    name: string,
    posts?:  {
      __typename: "ModelPostConnection",
      items:  Array< {
        __typename: "Post",
        id: string,
        title: string,
        gpxFile?: string | null,
        images?: string | null,
        headerImage?: string | null,
        date?: string | null,
        publishedDate?: string | null,
        location?: string | null,
        postLocation?: string | null,
        stravaUrl?: string | null,
        resultsUrl?: string | null,
        type?: string | null,
        subType?: string | null,
        teaser?: string | null,
        currentFtp?: string | null,
        components?: string | null,
        powerAnalysis?: string | null,
        coordinates?: string | null,
        powers?: string | null,
        elevation?: string | null,
        elevationGrades?: string | null,
        distances?: string | null,
        createdAt: string,
        updatedAt: string,
        blogPostsId?: string | null,
        postRelatedId?: string | null,
        postAuthorId?: string | null,
        owner?: string | null,
      } | null >,
      nextToken?: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    owner?: string | null,
  } | null,
};

export type OnCreatePostSubscriptionVariables = {
  filter?: ModelSubscriptionPostFilterInput | null,
  owner?: string | null,
};

export type OnCreatePostSubscription = {
  onCreatePost?:  {
    __typename: "Post",
    id: string,
    title: string,
    gpxFile?: string | null,
    images?: string | null,
    headerImage?: string | null,
    date?: string | null,
    publishedDate?: string | null,
    location?: string | null,
    postLocation?: string | null,
    stravaUrl?: string | null,
    resultsUrl?: string | null,
    type?: string | null,
    subType?: string | null,
    teaser?: string | null,
    currentFtp?: string | null,
    components?: string | null,
    powerAnalysis?: string | null,
    coordinates?: string | null,
    powers?: string | null,
    elevation?: string | null,
    elevationGrades?: string | null,
    distances?: string | null,
    blog?:  {
      __typename: "Blog",
      id: string,
      name: string,
      posts?:  {
        __typename: "ModelPostConnection",
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      owner?: string | null,
    } | null,
    related?:  {
      __typename: "ModelPostConnection",
      items:  Array< {
        __typename: "Post",
        id: string,
        title: string,
        gpxFile?: string | null,
        images?: string | null,
        headerImage?: string | null,
        date?: string | null,
        publishedDate?: string | null,
        location?: string | null,
        postLocation?: string | null,
        stravaUrl?: string | null,
        resultsUrl?: string | null,
        type?: string | null,
        subType?: string | null,
        teaser?: string | null,
        currentFtp?: string | null,
        components?: string | null,
        powerAnalysis?: string | null,
        coordinates?: string | null,
        powers?: string | null,
        elevation?: string | null,
        elevationGrades?: string | null,
        distances?: string | null,
        createdAt: string,
        updatedAt: string,
        blogPostsId?: string | null,
        postRelatedId?: string | null,
        postAuthorId?: string | null,
        owner?: string | null,
      } | null >,
      nextToken?: string | null,
    } | null,
    author?:  {
      __typename: "User",
      id: string,
      fullName: string,
      email: string,
      image?: string | null,
      username?: string | null,
      createdAt: string,
      updatedAt: string,
      owner?: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    blogPostsId?: string | null,
    postRelatedId?: string | null,
    postAuthorId?: string | null,
    owner?: string | null,
  } | null,
};

export type OnUpdatePostSubscriptionVariables = {
  filter?: ModelSubscriptionPostFilterInput | null,
  owner?: string | null,
};

export type OnUpdatePostSubscription = {
  onUpdatePost?:  {
    __typename: "Post",
    id: string,
    title: string,
    gpxFile?: string | null,
    images?: string | null,
    headerImage?: string | null,
    date?: string | null,
    publishedDate?: string | null,
    location?: string | null,
    postLocation?: string | null,
    stravaUrl?: string | null,
    resultsUrl?: string | null,
    type?: string | null,
    subType?: string | null,
    teaser?: string | null,
    currentFtp?: string | null,
    components?: string | null,
    powerAnalysis?: string | null,
    coordinates?: string | null,
    powers?: string | null,
    elevation?: string | null,
    elevationGrades?: string | null,
    distances?: string | null,
    blog?:  {
      __typename: "Blog",
      id: string,
      name: string,
      posts?:  {
        __typename: "ModelPostConnection",
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      owner?: string | null,
    } | null,
    related?:  {
      __typename: "ModelPostConnection",
      items:  Array< {
        __typename: "Post",
        id: string,
        title: string,
        gpxFile?: string | null,
        images?: string | null,
        headerImage?: string | null,
        date?: string | null,
        publishedDate?: string | null,
        location?: string | null,
        postLocation?: string | null,
        stravaUrl?: string | null,
        resultsUrl?: string | null,
        type?: string | null,
        subType?: string | null,
        teaser?: string | null,
        currentFtp?: string | null,
        components?: string | null,
        powerAnalysis?: string | null,
        coordinates?: string | null,
        powers?: string | null,
        elevation?: string | null,
        elevationGrades?: string | null,
        distances?: string | null,
        createdAt: string,
        updatedAt: string,
        blogPostsId?: string | null,
        postRelatedId?: string | null,
        postAuthorId?: string | null,
        owner?: string | null,
      } | null >,
      nextToken?: string | null,
    } | null,
    author?:  {
      __typename: "User",
      id: string,
      fullName: string,
      email: string,
      image?: string | null,
      username?: string | null,
      createdAt: string,
      updatedAt: string,
      owner?: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    blogPostsId?: string | null,
    postRelatedId?: string | null,
    postAuthorId?: string | null,
    owner?: string | null,
  } | null,
};

export type OnDeletePostSubscriptionVariables = {
  filter?: ModelSubscriptionPostFilterInput | null,
  owner?: string | null,
};

export type OnDeletePostSubscription = {
  onDeletePost?:  {
    __typename: "Post",
    id: string,
    title: string,
    gpxFile?: string | null,
    images?: string | null,
    headerImage?: string | null,
    date?: string | null,
    publishedDate?: string | null,
    location?: string | null,
    postLocation?: string | null,
    stravaUrl?: string | null,
    resultsUrl?: string | null,
    type?: string | null,
    subType?: string | null,
    teaser?: string | null,
    currentFtp?: string | null,
    components?: string | null,
    powerAnalysis?: string | null,
    coordinates?: string | null,
    powers?: string | null,
    elevation?: string | null,
    elevationGrades?: string | null,
    distances?: string | null,
    blog?:  {
      __typename: "Blog",
      id: string,
      name: string,
      posts?:  {
        __typename: "ModelPostConnection",
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      owner?: string | null,
    } | null,
    related?:  {
      __typename: "ModelPostConnection",
      items:  Array< {
        __typename: "Post",
        id: string,
        title: string,
        gpxFile?: string | null,
        images?: string | null,
        headerImage?: string | null,
        date?: string | null,
        publishedDate?: string | null,
        location?: string | null,
        postLocation?: string | null,
        stravaUrl?: string | null,
        resultsUrl?: string | null,
        type?: string | null,
        subType?: string | null,
        teaser?: string | null,
        currentFtp?: string | null,
        components?: string | null,
        powerAnalysis?: string | null,
        coordinates?: string | null,
        powers?: string | null,
        elevation?: string | null,
        elevationGrades?: string | null,
        distances?: string | null,
        createdAt: string,
        updatedAt: string,
        blogPostsId?: string | null,
        postRelatedId?: string | null,
        postAuthorId?: string | null,
        owner?: string | null,
      } | null >,
      nextToken?: string | null,
    } | null,
    author?:  {
      __typename: "User",
      id: string,
      fullName: string,
      email: string,
      image?: string | null,
      username?: string | null,
      createdAt: string,
      updatedAt: string,
      owner?: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    blogPostsId?: string | null,
    postRelatedId?: string | null,
    postAuthorId?: string | null,
    owner?: string | null,
  } | null,
};
